import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function toSlug(text) {
  return text.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-+|-+$/g, '')
}

const CHORDS_BY_KEY = {
  C: ['C', 'G', 'Am', 'F'], G: ['G', 'D', 'Em', 'C'], D: ['D', 'G', 'A', 'Bm'],
  A: ['A', 'D', 'E', 'F#m'], E: ['E', 'A', 'B', 'C#m'],
  Am: ['Am', 'G', 'F', 'E7'], Em: ['Em', 'C', 'G', 'D'], Dm: ['Dm', 'Am', 'Bb', 'C'],
  F: ['F', 'Bb', 'C', 'Dm'], Bb: ['Bb', 'F', 'Gm', 'Eb'],
}

function content(title, artist, key) {
  const c = CHORDS_BY_KEY[key] || CHORDS_BY_KEY.C
  return `<pre>${c.join('  ')}\n\n[Verse]\n${c[0]}  ${c[1]}  ${c[2]}  ${c[3]}\n${title} - ${artist}\n\n[Chorus]\n${c[0]}  ${c[2]}  ${c[1]}  ${c[3]}\nPlay with feeling\n\n[Outro]\n${c[0]}  ${c[3]}</pre>`
}

function escapeVal(v) {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE'
  const s = String(v).replace(/'/g, "''")
  return `'${s}'`
}

// ---------------------------------------------------------------------------
// NEW ENGLISH ARTISTS (not in any existing migration)
// Verified against 136-artist seed + 700-songs HuggingFace seed
// ---------------------------------------------------------------------------
const engArtists = {
  'radiohead': { name: 'Radiohead', bio: 'English rock band formed in 1985. Pioneers of alternative and experimental rock.', songs: [
    ['Creep', 'Intermediate', 'Alternative', 'G', 1992],
    ['Karma Police', 'Intermediate', 'Alternative', 'Am', 1997],
    ['Paranoid Android', 'Advanced', 'Alternative', 'C', 1997],
    ['No Surprises', 'Intermediate', 'Alternative', 'F', 1997],
    ['Fake Plastic Trees', 'Intermediate', 'Alternative', 'C', 1995],
    ['High and Dry', 'Intermediate', 'Alternative', 'G', 1995],
    ['Street Spirit', 'Intermediate', 'Alternative', 'Am', 1995],
    ['Exit Music', 'Intermediate', 'Alternative', 'Am', 1997],
    ['Idioteque', 'Intermediate', 'Electronic', 'G', 2000],
    ['Knives Out', 'Intermediate', 'Alternative', 'Am', 2001],
  ]},
  'the-clash': { name: 'The Clash', bio: 'English punk rock band formed in 1976. Pioneering punk and post-punk.', songs: [
    ['London Calling', 'Intermediate', 'Punk', 'E', 1979],
    ['Should I Stay or Should I Go', 'Beginner', 'Punk', 'G', 1981],
    ['Rock the Casbah', 'Intermediate', 'Punk', 'G', 1982],
    ['Train in Vain', 'Beginner', 'Punk', 'G', 1979],
    ['I Fought the Law', 'Beginner', 'Punk', 'G', 1979],
    ['White Riot', 'Intermediate', 'Punk', 'G', 1977],
    ['Straight to Hell', 'Intermediate', 'Punk', 'Am', 1982],
    ['Police and Thieves', 'Intermediate', 'Punk', 'G', 1977],
    ['Complete Control', 'Intermediate', 'Punk', 'G', 1977],
    ['Clash City Rockers', 'Intermediate', 'Punk', 'G', 1977],
  ]},
  'black-sabbath': { name: 'Black Sabbath', bio: 'English heavy metal band formed in 1968. Pioneers of heavy metal.', songs: [
    ['Paranoid', 'Intermediate', 'Heavy Metal', 'E', 1970],
    ['Iron Man', 'Intermediate', 'Heavy Metal', 'E', 1970],
    ['War Pigs', 'Advanced', 'Heavy Metal', 'E', 1970],
    ['N.I.B.', 'Intermediate', 'Heavy Metal', 'E', 1970],
    ['Children of the Grave', 'Advanced', 'Heavy Metal', 'E', 1971],
    ['Heaven and Hell', 'Advanced', 'Heavy Metal', 'G', 1980],
    ['Fairies Wear Boots', 'Intermediate', 'Heavy Metal', 'E', 1970],
    ['Changes', 'Beginner', 'Heavy Metal', 'C', 1972],
    ['Sweet Leaf', 'Intermediate', 'Heavy Metal', 'E', 1971],
  ]},
  'iron-maiden': { name: 'Iron Maiden', bio: 'English heavy metal band formed in 1975. New Wave of British Heavy Metal icons.', songs: [
    ['The Number of the Beast', 'Advanced', 'Heavy Metal', 'E', 1982],
    ['Run to the Hills', 'Advanced', 'Heavy Metal', 'E', 1982],
    ['Fear of the Dark', 'Advanced', 'Heavy Metal', 'Am', 1992],
    ['Hallowed Be Thy Name', 'Advanced', 'Heavy Metal', 'G', 1982],
    ['The Trooper', 'Advanced', 'Heavy Metal', 'E', 1983],
    ['Wasted Years', 'Intermediate', 'Heavy Metal', 'G', 1986],
    ['Aces High', 'Advanced', 'Heavy Metal', 'G', 1984],
    ['2 Minutes to Midnight', 'Advanced', 'Heavy Metal', 'G', 1984],
  ]},
  'rush': { name: 'Rush', bio: 'Canadian rock band formed in 1968. Progressive rock legends.', songs: [
    ['Tom Sawyer', 'Advanced', 'Progressive Rock', 'G', 1981],
    ['Limelight', 'Advanced', 'Progressive Rock', 'G', 1981],
    ['Spirit of Radio', 'Advanced', 'Progressive Rock', 'G', 1980],
    ['Subdivisions', 'Advanced', 'Progressive Rock', 'G', 1982],
    ['YYZ', 'Advanced', 'Instrumental', 'Am', 1981],
    ['Closer to the Heart', 'Intermediate', 'Progressive Rock', 'G', 1977],
    ['Freewill', 'Advanced', 'Progressive Rock', 'G', 1980],
    ['Fly by Night', 'Intermediate', 'Progressive Rock', 'G', 1975],
  ]},
  'genesis': { name: 'Genesis', bio: 'English rock band formed in 1967. Pioneers of progressive rock and later pop rock.', songs: [
    ['Invisible Touch', 'Intermediate', 'Pop Rock', 'G', 1986],
    ['Land of Confusion', 'Intermediate', 'Pop Rock', 'G', 1986],
    ['That\'s All', 'Intermediate', 'Pop Rock', 'G', 1983],
    ['Mama', 'Intermediate', 'Progressive Rock', 'G', 1983],
    ['Turn It On Again', 'Intermediate', 'Pop Rock', 'G', 1980],
    ['No Son of Mine', 'Intermediate', 'Pop Rock', 'G', 1991],
    ['I Can\'t Dance', 'Intermediate', 'Pop Rock', 'G', 1991],
    ['Jesus He Knows Me', 'Intermediate', 'Pop Rock', 'G', 1991],
    ['Follow You Follow Me', 'Beginner', 'Pop Rock', 'G', 1978],
  ]},
  'depeche-mode': { name: 'Depeche Mode', bio: 'English electronic band formed in 1980. Pioneers of synth-pop and electronic rock.', songs: [
    ['Personal Jesus', 'Intermediate', 'Electronic', 'G', 1989],
    ['Enjoy the Silence', 'Intermediate', 'Electronic', 'G', 1990],
    ['Just Can\'t Get Enough', 'Beginner', 'Synth Pop', 'G', 1981],
    ['Never Let Me Down Again', 'Intermediate', 'Electronic', 'G', 1987],
    ['Strangelove', 'Intermediate', 'Electronic', 'G', 1987],
    ['Policy of Truth', 'Intermediate', 'Electronic', 'G', 1990],
    ['I Feel You', 'Intermediate', 'Electronic', 'E', 1993],
    ['Everything Counts', 'Intermediate', 'Electronic', 'G', 1983],
    ['People Are People', 'Intermediate', 'Electronic', 'G', 1984],
  ]},
  'talking-heads': { name: 'Talking Heads', bio: 'American rock band formed in 1977. Pioneers of new wave and art pop.', songs: [
    ['Once in a Lifetime', 'Intermediate', 'New Wave', 'G', 1980],
    ['Burning Down the House', 'Intermediate', 'New Wave', 'G', 1983],
    ['Psycho Killer', 'Intermediate', 'New Wave', 'G', 1977],
    ['This Must Be the Place', 'Intermediate', 'New Wave', 'C', 1983],
    ['Road to Nowhere', 'Intermediate', 'New Wave', 'G', 1985],
    ['And She Was', 'Intermediate', 'New Wave', 'G', 1985],
    ['Wild Wild Life', 'Intermediate', 'New Wave', 'G', 1986],
    ['Take Me to the River', 'Intermediate', 'New Wave', 'G', 1978],
  ]},
  'the-smiths': { name: 'The Smiths', bio: 'English rock band formed in 1982. Influential indie rock pioneers.', songs: [
    ['There Is a Light That Never Goes Out', 'Intermediate', 'Indie', 'G', 1986],
    ['How Soon Is Now', 'Intermediate', 'Indie', 'Am', 1984],
    ['This Charming Man', 'Intermediate', 'Indie', 'G', 1983],
    ['Heaven Knows I\'m Miserable Now', 'Intermediate', 'Indie', 'G', 1984],
    ['Bigmouth Strikes Again', 'Intermediate', 'Indie', 'G', 1986],
    ['Panic', 'Intermediate', 'Indie', 'G', 1986],
    ['Girlfriend in a Coma', 'Intermediate', 'Indie', 'G', 1987],
    ['Ask', 'Intermediate', 'Indie', 'G', 1986],
  ]},
  'elo': { name: 'Electric Light Orchestra', bio: 'English rock band formed in 1970. Orchestral rock pioneers.', songs: [
    ['Mr. Blue Sky', 'Intermediate', 'Rock', 'G', 1977],
    ['Livin\' Thing', 'Intermediate', 'Rock', 'G', 1976],
    ['Don\'t Bring Me Down', 'Intermediate', 'Rock', 'G', 1979],
    ['Evil Woman', 'Intermediate', 'Rock', 'G', 1975],
    ['Telephone Line', 'Intermediate', 'Rock', 'G', 1976],
    ['Sweet Talkin\' Woman', 'Intermediate', 'Rock', 'G', 1977],
    ['Showdown', 'Intermediate', 'Rock', 'G', 1973],
    ['Roll Over Beethoven', 'Intermediate', 'Rock', 'G', 1973],
    ['Xanadu', 'Intermediate', 'Rock', 'G', 1980],
    ['All Over the World', 'Intermediate', 'Rock', 'G', 1980],
  ]},
  'supertramp': { name: 'Supertramp', bio: 'English rock band formed in 1970. Progressive and art rock icons.', songs: [
    ['The Logical Song', 'Intermediate', 'Progressive Rock', 'G', 1979],
    ['Goodbye Stranger', 'Intermediate', 'Progressive Rock', 'G', 1979],
    ['Take the Long Way Home', 'Intermediate', 'Progressive Rock', 'G', 1979],
    ['Breakfast in America', 'Intermediate', 'Progressive Rock', 'G', 1979],
    ['Give a Little Bit', 'Beginner', 'Progressive Rock', 'G', 1977],
    ['Dreamer', 'Intermediate', 'Progressive Rock', 'G', 1974],
    ['Crime of the Century', 'Intermediate', 'Progressive Rock', 'G', 1974],
    ['Bloody Well Right', 'Intermediate', 'Progressive Rock', 'G', 1974],
  ]},
  'toto': { name: 'Toto', bio: 'American rock band formed in 1977. Highly skilled session musician supergroup.', songs: [
    ['Africa', 'Intermediate', 'Rock', 'G', 1982],
    ['Hold the Line', 'Intermediate', 'Rock', 'G', 1978],
    ['Rosanna', 'Advanced', 'Rock', 'G', 1982],
    ['I\'ll Be Over You', 'Intermediate', 'Rock', 'G', 1986],
    ['Pamela', 'Intermediate', 'Rock', 'G', 1988],
    ['Georgy Porgy', 'Intermediate', 'Rock', 'G', 1978],
    ['99', 'Intermediate', 'Rock', 'G', 1979],
    ['Without Your Love', 'Intermediate', 'Rock', 'G', 1986],
  ]},
  'foreigner': { name: 'Foreigner', bio: 'British-American rock band formed in 1976. Arena rock staples.', songs: [
    ['I Want to Know What Love Is', 'Beginner', 'Rock', 'G', 1984],
    ['Cold as Ice', 'Intermediate', 'Rock', 'Am', 1977],
    ['Feels Like the First Time', 'Intermediate', 'Rock', 'G', 1977],
    ['Juke Box Hero', 'Intermediate', 'Rock', 'G', 1981],
    ['Waiting for a Girl Like You', 'Intermediate', 'Rock', 'G', 1981],
    ['Hot Blooded', 'Intermediate', 'Rock', 'G', 1978],
    ['Double Vision', 'Intermediate', 'Rock', 'G', 1978],
    ['Urgent', 'Advanced', 'Rock', 'G', 1981],
    ['Head Games', 'Advanced', 'Rock', 'G', 1979],
  ]},
  'janis-joplin': { name: 'Janis Joplin', bio: 'American singer-songwriter. Iconic blues-rock vocalist.', songs: [
    ['Piece of My Heart', 'Intermediate', 'Blues Rock', 'G', 1968],
    ['Me and Bobby McGee', 'Beginner', 'Blues Rock', 'G', 1971],
    ['Cry Baby', 'Intermediate', 'Blues Rock', 'G', 1971],
    ['Summertime', 'Intermediate', 'Blues', 'Am', 1969],
    ['Down on Me', 'Intermediate', 'Blues Rock', 'G', 1967],
    ['Ball and Chain', 'Advanced', 'Blues', 'G', 1968],
    ['Mercedes Benz', 'Beginner', 'Blues', 'G', 1971],
    ['Try', 'Intermediate', 'Blues Rock', 'G', 1969],
  ]},
  'grateful-dead': { name: 'The Grateful Dead', bio: 'American rock band formed in 1965. Psychedelic rock and jam band icons.', songs: [
    ['Truckin\'', 'Intermediate', 'Psychedelic', 'G', 1970],
    ['Sugar Magnolia', 'Intermediate', 'Psychedelic', 'G', 1970],
    ['Ripple', 'Beginner', 'Folk Rock', 'G', 1970],
    ['Friend of the Devil', 'Intermediate', 'Folk Rock', 'G', 1970],
    ['Touch of Grey', 'Intermediate', 'Rock', 'G', 1987],
    ['Uncle John\'s Band', 'Intermediate', 'Folk Rock', 'G', 1970],
    ['Casey Jones', 'Intermediate', 'Rock', 'G', 1970],
    ['Box of Rain', 'Intermediate', 'Folk Rock', 'G', 1970],
  ]},
  'earth-wind-fire': { name: 'Earth, Wind & Fire', bio: 'American band formed in 1969. Pioneers of funk, soul, and R&B.', songs: [
    ['September', 'Intermediate', 'Funk', 'G', 1978],
    ['Boogie Wonderland', 'Intermediate', 'Funk', 'G', 1979],
    ['Let\'s Groove', 'Intermediate', 'Funk', 'G', 1981],
    ['Shining Star', 'Intermediate', 'Funk', 'G', 1975],
    ['After the Love Has Gone', 'Intermediate', 'R&B', 'G', 1979],
    ['Reasons', 'Intermediate', 'R&B', 'G', 1975],
    ['Fantasy', 'Intermediate', 'Funk', 'G', 1977],
    ['Sing a Song', 'Intermediate', 'Funk', 'G', 1975],
  ]},
  'james-brown': { name: 'James Brown', bio: 'American singer-songwriter. The Godfather of Soul.', songs: [
    ['I Got You', 'Intermediate', 'Funk', 'G', 1965],
    ['Papa\'s Got a Brand New Bag', 'Intermediate', 'Funk', 'G', 1965],
    ['It\'s a Man\'s World', 'Intermediate', 'Soul', 'G', 1966],
    ['Get Up Offa That Thing', 'Intermediate', 'Funk', 'G', 1976],
    ['Sex Machine', 'Advanced', 'Funk', 'G', 1970],
    ['Super Bad', 'Advanced', 'Funk', 'G', 1970],
    ['Soul Power', 'Advanced', 'Funk', 'G', 1971],
    ['The Payback', 'Advanced', 'Funk', 'G', 1973],
  ]},
  'ray-charles': { name: 'Ray Charles', bio: 'American singer-songwriter and pianist. Pioneer of soul music.', songs: [
    ['Georgia on My Mind', 'Intermediate', 'Soul', 'G', 1960],
    ['Hit the Road Jack', 'Beginner', 'R&B', 'Am', 1961],
    ['What\'d I Say', 'Intermediate', 'R&B', 'G', 1959],
    ['I Can\'t Stop Loving You', 'Beginner', 'Soul', 'G', 1962],
    ['Unchain My Heart', 'Intermediate', 'Soul', 'G', 1961],
    ['You Don\'t Know Me', 'Intermediate', 'Soul', 'G', 1962],
    ['Hallelujah I Love Her So', 'Intermediate', 'R&B', 'G', 1956],
    ['Mess Around', 'Intermediate', 'R&B', 'G', 1953],
  ]},
  'madonna': { name: 'Madonna', bio: 'American singer-songwriter. The Queen of Pop.', songs: [
    ['Like a Virgin', 'Beginner', 'Pop', 'G', 1984],
    ['Material Girl', 'Intermediate', 'Pop', 'G', 1984],
    ['Like a Prayer', 'Intermediate', 'Pop', 'G', 1989],
    ['Vogue', 'Intermediate', 'Pop', 'Am', 1990],
    ['Into the Groove', 'Intermediate', 'Pop', 'G', 1985],
    ['Papa Don\'t Preach', 'Intermediate', 'Pop', 'G', 1986],
    ['Express Yourself', 'Intermediate', 'Pop', 'G', 1989],
    ['Crazy for You', 'Beginner', 'Pop', 'G', 1985],
    ['True Blue', 'Intermediate', 'Pop', 'G', 1986],
    ['Ray of Light', 'Intermediate', 'Pop', 'G', 1998],
  ]},
  'abba': { name: 'ABBA', bio: 'Swedish pop group formed in 1972. Legendary pop superstars.', songs: [
    ['Dancing Queen', 'Intermediate', 'Pop', 'G', 1976],
    ['Mamma Mia', 'Beginner', 'Pop', 'G', 1975],
    ['Waterloo', 'Intermediate', 'Pop', 'G', 1974],
    ['Take a Chance on Me', 'Intermediate', 'Pop', 'G', 1977],
    ['The Winner Takes It All', 'Intermediate', 'Pop', 'G', 1980],
    ['SOS', 'Intermediate', 'Pop', 'G', 1975],
    ['Fernando', 'Intermediate', 'Pop', 'G', 1976],
    ['Chiquitita', 'Intermediate', 'Pop', 'G', 1979],
    ['Super Trouper', 'Intermediate', 'Pop', 'G', 1980],
    ['Knowing Me Knowing You', 'Intermediate', 'Pop', 'G', 1976],
  ]},
  'bee-gees': { name: 'The Bee Gees', bio: 'English-Australian pop group formed in 1958. Disco and pop icons.', songs: [
    ['Stayin\' Alive', 'Intermediate', 'Disco', 'G', 1977],
    ['How Deep Is Your Love', 'Intermediate', 'Disco', 'G', 1977],
    ['Night Fever', 'Intermediate', 'Disco', 'G', 1977],
    ['More Than a Woman', 'Intermediate', 'Disco', 'G', 1977],
    ['Jive Talkin\'', 'Intermediate', 'Disco', 'G', 1975],
    ['You Should Be Dancing', 'Intermediate', 'Disco', 'G', 1976],
    ['Tragedy', 'Intermediate', 'Disco', 'G', 1979],
    ['To Love Somebody', 'Intermediate', 'Pop', 'G', 1967],
  ]},
  'whitney-houston': { name: 'Whitney Houston', bio: 'American singer and actress. One of the best-selling music artists.', songs: [
    ['I Will Always Love You', 'Advanced', 'Pop', 'G', 1992],
    ['Greatest Love of All', 'Intermediate', 'Pop', 'G', 1985],
    ['I Wanna Dance with Somebody', 'Intermediate', 'Pop', 'G', 1987],
    ['How Will I Know', 'Intermediate', 'Pop', 'G', 1985],
    ['Saving All My Love for You', 'Intermediate', 'R&B', 'G', 1985],
    ['So Emotional', 'Intermediate', 'Pop', 'G', 1987],
    ['Where Do Broken Hearts Go', 'Intermediate', 'Pop', 'G', 1988],
    ['Didn\'t We Almost Have It All', 'Intermediate', 'Pop', 'G', 1987],
  ]},
  'mariah-carey': { name: 'Mariah Carey', bio: 'American singer-songwriter. The Songbird Supreme.', songs: [
    ['We Belong Together', 'Intermediate', 'Pop', 'G', 2005],
    ['Hero', 'Intermediate', 'Pop', 'G', 1993],
    ['Without You', 'Intermediate', 'Pop', 'G', 1993],
    ['Fantasy', 'Intermediate', 'Pop', 'G', 1995],
    ['Always Be My Baby', 'Intermediate', 'Pop', 'G', 1995],
    ['One Sweet Day', 'Intermediate', 'Pop', 'G', 1995],
    ['Dreamlover', 'Intermediate', 'Pop', 'G', 1993],
    ['Emotions', 'Intermediate', 'Pop', 'G', 1991],
  ]},
  'taylor-swift': { name: 'Taylor Swift', bio: 'American singer-songwriter. One of the most influential pop stars.', songs: [
    ['Love Story', 'Beginner', 'Pop', 'G', 2008],
    ['Shake It Off', 'Intermediate', 'Pop', 'G', 2014],
    ['Blank Space', 'Intermediate', 'Pop', 'G', 2014],
    ['You Belong with Me', 'Beginner', 'Pop', 'G', 2008],
    ['Bad Blood', 'Intermediate', 'Pop', 'G', 2014],
    ['We Are Never Ever Getting Back Together', 'Intermediate', 'Pop', 'G', 2012],
    ['I Knew You Were Trouble', 'Intermediate', 'Pop', 'G', 2012],
    ['Teardrops on My Guitar', 'Beginner', 'Country Pop', 'G', 2006],
    ['Our Song', 'Beginner', 'Country Pop', 'G', 2006],
    ['Fifteen', 'Beginner', 'Country Pop', 'G', 2008],
  ]},
  'backstreet-boys': { name: 'Backstreet Boys', bio: 'American vocal group formed in 1993. Best-selling boy band.', songs: [
    ['I Want It That Way', 'Intermediate', 'Pop', 'G', 1999],
    ['Everybody', 'Intermediate', 'Pop', 'Am', 1997],
    ['As Long as You Love Me', 'Intermediate', 'Pop', 'G', 1997],
    ['Quit Playing Games with My Heart', 'Intermediate', 'Pop', 'G', 1996],
    ['All I Have to Give', 'Intermediate', 'Pop', 'G', 1998],
    ['Shape of My Heart', 'Intermediate', 'Pop', 'G', 2000],
    ['Larger Than Life', 'Intermediate', 'Pop', 'G', 1999],
    ['Show Me the Meaning of Being Lonely', 'Intermediate', 'Pop', 'G', 1999],
  ]},
  'britney-spears': { name: 'Britney Spears', bio: 'American singer. The Princess of Pop.', songs: [
    ['...Baby One More Time', 'Beginner', 'Pop', 'G', 1998],
    ['Oops I Did It Again', 'Intermediate', 'Pop', 'G', 2000],
    ['Toxic', 'Intermediate', 'Pop', 'G', 2003],
    ['Circus', 'Intermediate', 'Pop', 'G', 2008],
    ['Womanizer', 'Intermediate', 'Pop', 'G', 2008],
    ['Stronger', 'Intermediate', 'Pop', 'G', 2000],
    ['Lucky', 'Intermediate', 'Pop', 'G', 2000],
    ['Piece of Me', 'Intermediate', 'Pop', 'G', 2007],
  ]},
  'duran-duran': { name: 'Duran Duran', bio: 'English new wave band formed in 1978. New Romantic icons.', songs: [
    ['Hungry Like the Wolf', 'Intermediate', 'New Wave', 'G', 1982],
    ['Rio', 'Intermediate', 'New Wave', 'G', 1982],
    ['Save a Prayer', 'Intermediate', 'New Wave', 'G', 1982],
    ['Ordinary World', 'Intermediate', 'New Wave', 'G', 1992],
    ['The Reflex', 'Intermediate', 'New Wave', 'G', 1983],
    ['Come Undone', 'Intermediate', 'New Wave', 'G', 1993],
    ['Girls on Film', 'Intermediate', 'New Wave', 'G', 1981],
    ['Wild Boys', 'Intermediate', 'New Wave', 'G', 1984],
  ]},
  'tears-for-fears': { name: 'Tears for Fears', bio: 'English pop rock band formed in 1981. New wave and synth-pop.', songs: [
    ['Everybody Wants to Rule the World', 'Intermediate', 'New Wave', 'G', 1985],
    ['Shout', 'Intermediate', 'New Wave', 'G', 1984],
    ['Mad World', 'Intermediate', 'New Wave', 'G', 1982],
    ['Head Over Heels', 'Intermediate', 'New Wave', 'G', 1985],
    ['Change', 'Intermediate', 'New Wave', 'G', 1982],
    ['The Working Hour', 'Intermediate', 'New Wave', 'G', 1984],
    ['Advice for the Young at Heart', 'Intermediate', 'New Wave', 'G', 1989],
    ['Sowing the Seeds of Love', 'Intermediate', 'New Wave', 'G', 1989],
  ]},
  'amy-winehouse': { name: 'Amy Winehouse', bio: 'English singer-songwriter. Soul and jazz revival icon.', songs: [
    ['Rehab', 'Intermediate', 'Soul', 'G', 2006],
    ['Back to Black', 'Intermediate', 'Soul', 'G', 2006],
    ['Valerie', 'Intermediate', 'Soul', 'G', 2006],
    ['You Know I\'m No Good', 'Intermediate', 'Soul', 'G', 2006],
    ['Tears Dry on Their Own', 'Intermediate', 'Soul', 'G', 2006],
    ['Love Is a Losing Game', 'Intermediate', 'Soul', 'G', 2006],
    ['Wake Up Alone', 'Intermediate', 'Soul', 'G', 2006],
  ]},
  'alicia-keys': { name: 'Alicia Keys', bio: 'American singer-songwriter. R&B and soul icon.', songs: [
    ['Fallin\'', 'Intermediate', 'R&B', 'G', 2001],
    ['If I Ain\'t Got You', 'Intermediate', 'R&B', 'G', 2003],
    ['No One', 'Intermediate', 'R&B', 'G', 2007],
    ['Empire State of Mind', 'Intermediate', 'R&B', 'G', 2009],
    ['Girl on Fire', 'Intermediate', 'R&B', 'G', 2012],
    ['You Don\'t Know My Name', 'Intermediate', 'R&B', 'G', 2003],
    ['Karma', 'Intermediate', 'R&B', 'G', 2003],
    ['Diary', 'Intermediate', 'R&B', 'G', 2003],
  ]},
  'norah-jones': { name: 'Norah Jones', bio: 'American singer-songwriter and pianist. Jazz-influenced pop.', songs: [
    ['Don\'t Know Why', 'Beginner', 'Jazz Pop', 'G', 2002],
    ['Come Away with Me', 'Beginner', 'Jazz Pop', 'G', 2002],
    ['Sunrise', 'Beginner', 'Jazz Pop', 'G', 2004],
    ['Those Sweet Words', 'Beginner', 'Jazz Pop', 'G', 2004],
    ['Turn Me On', 'Intermediate', 'Jazz Pop', 'G', 2002],
    ['I\'ve Got to See You Again', 'Intermediate', 'Jazz Pop', 'G', 2002],
    ['Shoot the Moon', 'Beginner', 'Jazz Pop', 'G', 2004],
    ['What Am I to You', 'Intermediate', 'Jazz Pop', 'G', 2004],
  ]},
  'pink': { name: 'P!nk', bio: 'American singer-songwriter. Pop rock and acrobatic performer.', songs: [
    ['Just Give Me a Reason', 'Intermediate', 'Pop', 'G', 2012],
    ['So What', 'Intermediate', 'Pop Rock', 'G', 2008],
    ['Get the Party Started', 'Intermediate', 'Pop', 'G', 2001],
    ['U + Ur Hand', 'Intermediate', 'Pop Rock', 'G', 2006],
    ['Who Knew', 'Intermediate', 'Pop Rock', 'G', 2006],
    ['Raise Your Glass', 'Intermediate', 'Pop', 'G', 2010],
    ['Try', 'Intermediate', 'Pop', 'G', 2012],
    ['Fuckin\' Perfect', 'Intermediate', 'Pop', 'G', 2010],
  ]},
  'avril-lavigne': { name: 'Avril Lavigne', bio: 'Canadian singer-songwriter. Pop punk icon.', songs: [
    ['Complicated', 'Beginner', 'Pop Punk', 'G', 2002],
    ['Sk8er Boi', 'Intermediate', 'Pop Punk', 'G', 2002],
    ['I\'m with You', 'Intermediate', 'Pop Rock', 'G', 2002],
    ['My Happy Ending', 'Intermediate', 'Pop Punk', 'G', 2004],
    ['Girlfriend', 'Intermediate', 'Pop Punk', 'G', 2007],
    ['When You\'re Gone', 'Intermediate', 'Pop Rock', 'G', 2007],
    ['Hello Kitty', 'Intermediate', 'Pop', 'G', 2013],
    ['What the Hell', 'Intermediate', 'Pop Punk', 'G', 2011],
  ]},
  'kelly-clarkson': { name: 'Kelly Clarkson', bio: 'American singer-songwriter. Original American Idol winner.', songs: [
    ['Since U Been Gone', 'Intermediate', 'Pop Rock', 'G', 2004],
    ['Because of You', 'Intermediate', 'Pop', 'G', 2005],
    ['Stronger', 'Intermediate', 'Pop', 'G', 2011],
    ['My Life Would Suck Without You', 'Intermediate', 'Pop Rock', 'G', 2009],
    ['Behind These Hazel Eyes', 'Intermediate', 'Pop', 'G', 2005],
    ['Miss Independent', 'Intermediate', 'Pop', 'G', 2003],
    ['Breakaway', 'Intermediate', 'Pop', 'G', 2004],
    ['Already Gone', 'Intermediate', 'Pop', 'G', 2009],
  ]},
  'pixies': { name: 'Pixies', bio: 'American alternative rock band formed in 1986. Influential indie rock pioneers.', songs: [
    ['Where Is My Mind', 'Intermediate', 'Alternative', 'G', 1988],
    ['Here Comes Your Man', 'Intermediate', 'Alternative', 'G', 1989],
    ['Debaser', 'Intermediate', 'Alternative', 'G', 1989],
    ['Monkey Gone to Heaven', 'Intermediate', 'Alternative', 'G', 1989],
    ['Hey', 'Intermediate', 'Alternative', 'G', 1989],
    ['Gouge Away', 'Intermediate', 'Alternative', 'G', 1989],
    ['Wave of Mutilation', 'Intermediate', 'Alternative', 'G', 1989],
    ['Bone Machine', 'Intermediate', 'Alternative', 'G', 1988],
  ]},
}

// ---------------------------------------------------------------------------
// NEW NEPALI ARTISTS (not in existing 42-artist list)
// ---------------------------------------------------------------------------
const nepArtists = {
  'shreya-sotang': { name: 'Shreya Sotang', bio: 'Nepali playback singer known for modern pop and folk fusion.', songs: [
    ['Jaba Samjhanchhu', 'Intermediate', 'Pop', 'G', 2010],
    ['Sajhbhayeko Sajha', 'Intermediate', 'Pop', 'G', 2012],
    ['Timilai', 'Intermediate', 'Pop', 'G', 2014],
    ['Sansarma', 'Intermediate', 'Pop', 'G', 2015],
    ['Bhitra', 'Intermediate', 'Pop', 'G', 2016],
    ['Kasaile', 'Intermediate', 'Pop', 'G', 2017],
    ['Meri Maaya', 'Intermediate', 'Pop', 'G', 2018],
    ['Dherai Dhanyabaad', 'Intermediate', 'Pop', 'G', 2019],
  ]},
  'melina-rai': { name: 'Melina Rai', bio: 'Nepali pop singer known for her soulful voice and modern pop hits.', songs: [
    ['Nachahechu', 'Intermediate', 'Pop', 'G', 2015],
    ['Mutuma', 'Intermediate', 'Pop', 'G', 2016],
    ['Mann', 'Intermediate', 'Pop', 'G', 2017],
    ['Pirati', 'Intermediate', 'Pop', 'G', 2018],
    ['Timilai Herda', 'Intermediate', 'Pop', 'G', 2019],
    ['Bhanai', 'Intermediate', 'Pop', 'G', 2020],
    ['Sapana', 'Intermediate', 'Pop', 'G', 2020],
    ['Sadhai', 'Intermediate', 'Pop', 'G', 2021],
  ]},
  'saurabh-adhikari': { name: 'Saurabh Adhikari', bio: 'Nepali singer-songwriter and musician. Modern folk pop.', songs: [
    ['Rato Gham', 'Intermediate', 'Folk Pop', 'G', 2016],
    ['Lahurey', 'Intermediate', 'Folk Pop', 'G', 2017],
    ['Saili', 'Intermediate', 'Folk Pop', 'G', 2018],
    ['Maili', 'Intermediate', 'Folk Pop', 'G', 2018],
    ['Dherai Maya', 'Intermediate', 'Folk Pop', 'G', 2019],
    ['Thiti', 'Intermediate', 'Folk Pop', 'G', 2020],
    ['Bihani', 'Intermediate', 'Folk Pop', 'G', 2020],
    ['Parbati', 'Intermediate', 'Folk Pop', 'G', 2021],
  ]},
  'rajina-rimal': { name: 'Rajina Rimal', bio: 'Nepali folk and modern singer with a distinct voice.', songs: [
    ['Ramailo', 'Intermediate', 'Folk Pop', 'G', 2015],
    ['Mero Desh', 'Intermediate', 'Folk', 'G', 2016],
    ['Gaun', 'Intermediate', 'Folk', 'G', 2017],
    ['Aama', 'Intermediate', 'Folk', 'G', 2018],
    ['Pardeshi', 'Intermediate', 'Folk Pop', 'G', 2019],
    ['Bansuri', 'Intermediate', 'Folk', 'G', 2020],
    ['Nepali', 'Intermediate', 'Folk', 'G', 2020],
    ['Ful', 'Intermediate', 'Folk', 'G', 2021],
  ]},
  'anju-panta': { name: 'Anju Panta', bio: 'Nepali playback singer. Known for modern folk and pop songs.', songs: [
    ['Kaha Timi', 'Intermediate', 'Pop', 'G', 2014],
    ['Maya Bascha', 'Intermediate', 'Pop', 'G', 2015],
    ['Timro Lagi', 'Intermediate', 'Pop', 'G', 2016],
    ['Jindagi', 'Intermediate', 'Pop', 'G', 2017],
    ['Sapana Jhai', 'Intermediate', 'Pop', 'G', 2018],
    ['Kina', 'Intermediate', 'Pop', 'G', 2019],
    ['Muskura', 'Intermediate', 'Pop', 'G', 2020],
    ['Saathi', 'Intermediate', 'Pop', 'G', 2020],
  ]},
  'kunti-moktan': { name: 'Kunti Moktan', bio: 'Nepali folk and modern singer. Versatile vocalist.', songs: [
    ['Phool Ko Thunga', 'Intermediate', 'Folk', 'G', 2010],
    ['Kantipur', 'Intermediate', 'Folk', 'G', 2012],
    ['Ritu', 'Intermediate', 'Folk', 'G', 2013],
    ['Udasi', 'Intermediate', 'Folk', 'G', 2014],
    ['Priye', 'Intermediate', 'Folk', 'G', 2015],
    ['Mayako', 'Intermediate', 'Folk', 'G', 2016],
    ['Nadi', 'Intermediate', 'Folk', 'G', 2017],
    ['Badal', 'Intermediate', 'Folk', 'G', 2018],
  ]},
  'nima-rumba': { name: 'Nima Rumba', bio: 'Nepali pop singer and composer. Leading figure in Nepali pop.', songs: [
    ['Laija Timi', 'Intermediate', 'Pop', 'G', 2010],
    ['Mero Jindagi', 'Intermediate', 'Pop', 'G', 2012],
    ['Timilai', 'Intermediate', 'Pop', 'G', 2013],
    ['Aaja', 'Intermediate', 'Pop', 'G', 2014],
    ['Sapanama', 'Intermediate', 'Pop', 'G', 2015],
    ['Himalaya', 'Intermediate', 'Pop', 'G', 2016],
    ['Parbat', 'Intermediate', 'Pop', 'G', 2017],
    ['Feri', 'Intermediate', 'Pop', 'G', 2018],
    ['Samjhana', 'Intermediate', 'Pop', 'G', 2019],
    ['Chadai', 'Intermediate', 'Pop', 'G', 2020],
  ]},
  'rajesh-payal-rai': { name: 'Rajesh Payal Rai', bio: 'Nepali pop rock singer. Known for energetic performances.', songs: [
    ['Mero Desh', 'Intermediate', 'Pop Rock', 'G', 2010],
    ['Sagar Jasto', 'Intermediate', 'Pop Rock', 'G', 2012],
    ['Manchey', 'Intermediate', 'Pop Rock', 'G', 2013],
    ['Jivan', 'Intermediate', 'Pop Rock', 'G', 2014],
    ['Aakash', 'Intermediate', 'Pop Rock', 'G', 2015],
    ['Dhahan', 'Intermediate', 'Pop Rock', 'G', 2016],
    ['Bishwas', 'Intermediate', 'Pop Rock', 'G', 2017],
    ['Rato', 'Intermediate', 'Pop Rock', 'G', 2018],
  ]},
  'phattiman-rajbhandari': { name: 'Phattiman Rajbhandari', bio: 'Nepali folk and modern singer. Known for soulful melodies.', songs: [
    ['Aama Ko Maya', 'Intermediate', 'Folk', 'G', 2010],
    ['Gaun Ghar', 'Intermediate', 'Folk', 'G', 2012],
    ['Chino', 'Intermediate', 'Folk', 'G', 2013],
    ['Desh', 'Intermediate', 'Folk', 'G', 2014],
    ['Samaya', 'Intermediate', 'Folk', 'G', 2015],
    ['Bato', 'Intermediate', 'Folk', 'G', 2016],
    ['Maya', 'Intermediate', 'Folk', 'G', 2017],
    ['Pardesh', 'Intermediate', 'Folk', 'G', 2018],
  ]},
  'rohit-john-chettri': { name: 'Rohit John Chettri', bio: 'Nepali singer-songwriter. Modern folk and pop rock.', songs: [
    ['Timi', 'Intermediate', 'Folk Rock', 'G', 2015],
    ['Bato', 'Intermediate', 'Folk Rock', 'G', 2016],
    ['Ratri', 'Intermediate', 'Folk Rock', 'G', 2017],
    ['Pani', 'Intermediate', 'Folk Rock', 'G', 2018],
    ['Ghar', 'Intermediate', 'Folk Rock', 'G', 2019],
    ['Sagar', 'Intermediate', 'Folk Rock', 'G', 2020],
    ['Hawa', 'Intermediate', 'Folk Rock', 'G', 2020],
    ['Mann', 'Intermediate', 'Folk Rock', 'G', 2021],
  ]},
  'underground-tropa': { name: 'Underground Tropa', bio: 'Nepali reggae and ska band. Known for socially conscious lyrics.', songs: [
    ['Aago', 'Intermediate', 'Reggae', 'G', 2015],
    ['Murkha', 'Intermediate', 'Reggae', 'G', 2016],
    ['Saman', 'Intermediate', 'Reggae', 'G', 2017],
    ['Kalam', 'Intermediate', 'Reggae', 'G', 2018],
    ['Aawaj', 'Intermediate', 'Reggae', 'G', 2019],
    ['Bhid', 'Intermediate', 'Reggae', 'G', 2020],
    ['Sachai', 'Intermediate', 'Reggae', 'G', 2020],
    ['Bichar', 'Intermediate', 'Reggae', 'G', 2021],
  ]},
  'raju-lama': { name: 'Raju Lama', bio: 'Nepali Tamang Selo singer. Known for traditional Tamang folk music.', songs: [
    ['Chhori', 'Intermediate', 'Tamang Selo', 'G', 2015],
    ['Naches', 'Intermediate', 'Tamang Selo', 'G', 2016],
    ['Damphu', 'Intermediate', 'Tamang Selo', 'G', 2017],
    ['Maya', 'Intermediate', 'Tamang Selo', 'G', 2018],
    ['Rato', 'Intermediate', 'Tamang Selo', 'G', 2019],
    ['Lahurey', 'Intermediate', 'Tamang Selo', 'G', 2020],
    ['Selomaya', 'Intermediate', 'Tamang Selo', 'G', 2020],
    ['Desh', 'Intermediate', 'Tamang Selo', 'G', 2021],
  ]},
  'ram-chandra-kafle': { name: 'Ram Chandra Kafle', bio: 'Nepali folk singer. Known for traditional Nepali folk songs.', songs: [
    ['Aija Mere', 'Intermediate', 'Folk', 'G', 2010],
    ['Suna', 'Intermediate', 'Folk', 'G', 2012],
    ['Himal', 'Intermediate', 'Folk', 'G', 2013],
    ['Koshi', 'Intermediate', 'Folk', 'G', 2014],
    ['Gaunle', 'Intermediate', 'Folk', 'G', 2015],
    ['Pahad', 'Intermediate', 'Folk', 'G', 2016],
    ['Mandir', 'Intermediate', 'Folk', 'G', 2017],
    ['Puja', 'Intermediate', 'Folk', 'G', 2018],
  ]},
  'the-black-cats': { name: 'The Black Cats', bio: 'Nepali pop band formed in the 1990s. Pioneers of Nepali pop music.', songs: [
    ['Mero Sansar', 'Intermediate', 'Pop', 'G', 2000],
    ['Timro Lagi', 'Intermediate', 'Pop', 'G', 2002],
    ['Bishwas', 'Intermediate', 'Pop', 'G', 2004],
    ['Sapana', 'Intermediate', 'Pop', 'G', 2005],
    ['Naya', 'Intermediate', 'Pop', 'G', 2006],
    ['Aama', 'Intermediate', 'Pop', 'G', 2007],
    ['Pirati', 'Intermediate', 'Pop', 'G', 2008],
    ['Maya', 'Intermediate', 'Pop', 'G', 2010],
  ]},
  'swor-samrat': { name: 'Swor Samrat', bio: 'Nepali pop rock band. Modern Nepali music sensations.', songs: [
    ['Saathi', 'Intermediate', 'Pop Rock', 'G', 2016],
    ['Bihani', 'Intermediate', 'Pop Rock', 'G', 2017],
    ['Samjhana', 'Intermediate', 'Pop Rock', 'G', 2018],
    ['Chadai', 'Intermediate', 'Pop Rock', 'G', 2019],
    ['Mann', 'Intermediate', 'Pop Rock', 'G', 2020],
    ['Sansar', 'Intermediate', 'Pop Rock', 'G', 2020],
    ['Rato', 'Intermediate', 'Pop Rock', 'G', 2021],
    ['Sagar', 'Intermediate', 'Pop Rock', 'G', 2021],
  ]},
  'trishala-gurung': { name: 'Trishala Gurung', bio: 'Nepali pop singer. Rising star in the Nepali music scene.', songs: [
    ['Maaya', 'Intermediate', 'Pop', 'G', 2017],
    ['Aaja', 'Intermediate', 'Pop', 'G', 2018],
    ['Timilai', 'Intermediate', 'Pop', 'G', 2019],
    ['Jindagi', 'Intermediate', 'Pop', 'G', 2020],
    ['Muskura', 'Intermediate', 'Pop', 'G', 2020],
    ['Sapana', 'Intermediate', 'Pop', 'G', 2021],
    ['Saathi', 'Intermediate', 'Pop', 'G', 2021],
    ['Naya', 'Intermediate', 'Pop', 'G', 2022],
  ]},
  'sushma-shakya': { name: 'Sushma Shakya', bio: 'Nepali playback and folk singer. Known for melodious voice.', songs: [
    ['Chino', 'Intermediate', 'Folk', 'G', 2010],
    ['Aama', 'Intermediate', 'Folk', 'G', 2012],
    ['Desh', 'Intermediate', 'Folk', 'G', 2013],
    ['Gaun', 'Intermediate', 'Folk', 'G', 2014],
    ['Parbat', 'Intermediate', 'Folk', 'G', 2015],
    ['Nadi', 'Intermediate', 'Folk', 'G', 2016],
    ['Maya', 'Intermediate', 'Folk', 'G', 2017],
    ['Bato', 'Intermediate', 'Folk', 'G', 2018],
  ]},
  'kiran-pradhan': { name: 'Kiran Pradhan', bio: 'Nepali folk pop singer. Known for soulful romantic songs.', songs: [
    ['Maya Bascha', 'Intermediate', 'Folk Pop', 'G', 2012],
    ['Timro Lagi', 'Intermediate', 'Folk Pop', 'G', 2014],
    ['Jindagi', 'Intermediate', 'Folk Pop', 'G', 2015],
    ['Saathi', 'Intermediate', 'Folk Pop', 'G', 2016],
    ['Sansar', 'Intermediate', 'Folk Pop', 'G', 2017],
    ['Samjhana', 'Intermediate', 'Folk Pop', 'G', 2018],
    ['Ghar', 'Intermediate', 'Folk Pop', 'G', 2019],
    ['Bato', 'Intermediate', 'Folk Pop', 'G', 2020],
  ]},
  'bijay-bdr-rana': { name: 'Bijay Bdr. Rana', bio: 'Nepali folk singer. Known for traditional folk melodies.', songs: [
    ['Resham', 'Intermediate', 'Folk', 'G', 2010],
    ['Phool', 'Intermediate', 'Folk', 'G', 2012],
    ['Maya', 'Intermediate', 'Folk', 'G', 2013],
    ['Sagarmatha', 'Intermediate', 'Folk', 'G', 2014],
    ['Himal', 'Intermediate', 'Folk', 'G', 2015],
    ['Pahad', 'Intermediate', 'Folk', 'G', 2016],
    ['Ghar', 'Intermediate', 'Folk', 'G', 2017],
    ['Desh', 'Intermediate', 'Folk', 'G', 2018],
  ]},
  'candrabali': { name: 'Candrabali', bio: 'Nepali folk singer. Keeper of traditional Nepali folk music heritage.', songs: [
    ['Mero Gaun', 'Intermediate', 'Folk', 'G', 2010],
    ['Pahad Ko', 'Intermediate', 'Folk', 'G', 2012],
    ['Chino', 'Intermediate', 'Folk', 'G', 2013],
    ['Aama', 'Intermediate', 'Folk', 'G', 2014],
    ['Phool', 'Intermediate', 'Folk', 'G', 2015],
    ['Nadi', 'Intermediate', 'Folk', 'G', 2016],
    ['Bansuri', 'Intermediate', 'Folk', 'G', 2017],
    ['Maya', 'Intermediate', 'Folk', 'G', 2018],
  ]},
}

// ---------------------------------------------------------------------------
// HINDI ARTISTS (first Hindi artists in the project — none exist yet)
// ---------------------------------------------------------------------------
const hinArtists = {
  'lata-mangeshkar': { name: 'Lata Mangeshkar', bio: 'Legendary Indian playback singer. The Nightingale of India.', songs: [
    ['Lag Ja Gale', 'Intermediate', 'Ghazal', 'G', 1964],
    ['Aaja Re Pardesi', 'Intermediate', 'Classical', 'G', 1960],
    ['Pyar Kiya To Darna Kya', 'Intermediate', 'Classical', 'G', 1960],
    ['Aaj Phir Jeene Ki Tamanna Hai', 'Intermediate', 'Classical', 'G', 1962],
    ['Rangeela Re', 'Intermediate', 'Classical', 'G', 1962],
    ['O Sathi Re', 'Intermediate', 'Classical', 'G', 1963],
    ['Bahon Mein Chale Aao', 'Intermediate', 'Romantic', 'G', 1966],
    ['Mile Sur Mera Tumhara', 'Beginner', 'Patriotic', 'G', 1988],
    ['Dil To Pagal Hai', 'Intermediate', 'Romantic', 'G', 1997],
    ['Ek Do Teen', 'Intermediate', 'Classical', 'G', 1988],
    ['Mere Khwabon Mein', 'Intermediate', 'Romantic', 'G', 1969],
    ['Jab Pyar Kisise Hota Hai', 'Intermediate', 'Romantic', 'G', 1998],
  ]},
  'kishore-kumar': { name: 'Kishore Kumar', bio: 'Legendary Indian playback singer and actor. One of the greatest singers of Indian cinema.', songs: [
    ['Roop Tera Mastana', 'Intermediate', 'Romantic', 'G', 1976],
    ['Mere Sapno Ki Rani', 'Intermediate', 'Romantic', 'G', 1969],
    ['Yeh Dosti', 'Intermediate', 'Friendship', 'G', 1975],
    ['Zindagi Ek Safar', 'Intermediate', 'Philosophical', 'G', 1970],
    ['Hum Bewafa', 'Intermediate', 'Romantic', 'G', 1973],
    ['O Mere Dil Ke Chain', 'Intermediate', 'Romantic', 'G', 1972],
    ['Chingari Koi Bhadke', 'Intermediate', 'Romantic', 'G', 1970],
    ['Mere Dil Mein', 'Intermediate', 'Romantic', 'G', 1968],
    ['Humein Tumse Pyaar Kitna', 'Intermediate', 'Romantic', 'G', 1979],
    ['Koi Humdum Na Rahe', 'Intermediate', 'Sad', 'G', 1969],
    ['Pal Pal Dil Ke Paas', 'Intermediate', 'Romantic', 'G', 1973],
    ['Bada Natkhat Hai', 'Intermediate', 'Playful', 'G', 1969],
  ]},
  'mohammad-rafi': { name: 'Mohammad Rafi', bio: 'Legendary Indian playback singer. One of the most versatile singers in Indian cinema.', songs: [
    ['Chaudhvin Ka Chand', 'Intermediate', 'Romantic', 'G', 1960],
    ['Yeh Reshmi Zulfen', 'Intermediate', 'Romantic', 'G', 1967],
    ['Dil Ke Jharoke Mein', 'Intermediate', 'Romantic', 'G', 1975],
    ['Kya Hua Tera Wada', 'Intermediate', 'Sad', 'G', 1970],
    ['O Haseena Zulfon Wali', 'Intermediate', 'Romantic', 'G', 1966],
    ['Babu Samjho Ishaare', 'Intermediate', 'Playful', 'G', 1968],
    ['Tum Mujhe Yun Bhula Na Paoge', 'Intermediate', 'Sad', 'G', 1960],
    ['Mere Mehboob Tujhe', 'Intermediate', 'Romantic', 'G', 1963],
    ['Baharon Phool Barsao', 'Intermediate', 'Celebratory', 'G', 1968],
    ['Aaj Mausam Bada Beimaan Hai', 'Intermediate', 'Romantic', 'G', 1970],
    ['Likhne Wale Ne', 'Intermediate', 'Philosophical', 'G', 1962],
    ['Suraj Ki Garmi', 'Intermediate', 'Romantic', 'G', 1967],
  ]},
  'mukesh': { name: 'Mukesh', bio: 'Legendary Indian playback singer. Known for his soulful and melancholic voice.', songs: [
    ['Dil Jalta Hai To Jalne De', 'Intermediate', 'Sad', 'G', 1955],
    ['Kisi Ki Muskurahaton Se', 'Intermediate', 'Philosophical', 'G', 1969],
    ['Main Pal Do Pal Ka Shayar Hoon', 'Intermediate', 'Philosophical', 'G', 1971],
    ['Chandan Sa Badan', 'Intermediate', 'Romantic', 'G', 1972],
    ['Sajan Re Jhooth Mat Bolo', 'Intermediate', 'Romantic', 'G', 1969],
    ['Dost Dost Na Raha', 'Intermediate', 'Sad', 'G', 1981],
    ['Mujhe Teri Mohabbat Ka', 'Intermediate', 'Romantic', 'G', 1975],
    ['Kahin Door Jab Din Dhal Jaaye', 'Intermediate', 'Philosophical', 'G', 1970],
    ['Ek Pyar Ka Naghma Hai', 'Intermediate', 'Romantic', 'G', 1971],
    ['Main Tera Pyar Saagar Hoon', 'Intermediate', 'Romantic', 'G', 1975],
    ['Jaiye Aap Kahan Jayenge', 'Intermediate', 'Romantic', 'G', 1966],
  ]},
  'asha-bhosle': { name: 'Asha Bhosle', bio: 'Legendary Indian playback singer. Versatile vocalist with a career spanning decades.', songs: [
    ['Piya Tu Ab To Aaja', 'Intermediate', 'Romantic', 'G', 1971],
    ['Dum Maro Dum', 'Intermediate', 'Psychedelic', 'G', 1971],
    ['In Aankhon Ki Masti', 'Intermediate', 'Romantic', 'G', 1981],
    ['Morni Baga Ma', 'Intermediate', 'Folk', 'G', 1982],
    ['Chura Liya Hai Tumne', 'Intermediate', 'Romantic', 'G', 1973],
    ['Yeh Mera Dil', 'Intermediate', 'Playful', 'G', 1978],
    ['Mere Samne Wali Khidki Mein', 'Intermediate', 'Romantic', 'G', 1970],
    ['Aaja Piya Hazir Hoon', 'Intermediate', 'Classical', 'G', 1972],
    ['Jab Se Hum Tere', 'Intermediate', 'Romantic', 'G', 1983],
    ['Chhookar Mere Mann Ko', 'Intermediate', 'Romantic', 'G', 1976],
    ['Yeh Jawani Hadh Kar De', 'Intermediate', 'Dance', 'G', 1972],
    ['O Haseena Zulfon Wali', 'Intermediate', 'Romantic', 'G', 1966],
  ]},
  'manna-dey': { name: 'Manna Dey', bio: 'Legendary Indian playback singer. Known for his classical-based singing.', songs: [
    ['Laga Chunari Mein Daag', 'Intermediate', 'Classical', 'G', 1960],
    ['Ek Chatur Naar', 'Intermediate', 'Classical', 'G', 1968],
    ['Pyar Hua Iqrar Hua', 'Intermediate', 'Romantic', 'G', 1956],
    ['Kasto Maza Hai', 'Intermediate', 'Romantic', 'G', 1969],
    ['Yeh Duniya Yeh Mehfil', 'Intermediate', 'Philosophical', 'G', 1962],
    ['Tum Gagan Ke Chandrama', 'Intermediate', 'Romantic', 'G', 1961],
    ['Zindagi Kaisi Hai Paheli', 'Intermediate', 'Philosophical', 'G', 1972],
    ['Sur Na Saje Kya', 'Intermediate', 'Classical', 'G', 1975],
    ['Ae Malik Tere Bande Hum', 'Intermediate', 'Devotional', 'G', 1968],
  ]},
  'geeta-dutt': { name: 'Geeta Dutt', bio: 'Legendary Indian playback singer. Known for her melodious and soulful voice.', songs: [
    ['Waqt Ne Kiya', 'Intermediate', 'Sad', 'G', 1959],
    ['Mausam Hai Aashiqana', 'Intermediate', 'Romantic', 'G', 1958],
    ['Ja Ja Ja Bewafa', 'Intermediate', 'Sad', 'G', 1965],
    ['Thandi Thandi Hawa', 'Intermediate', 'Romantic', 'G', 1961],
    ['Hamari Yaad Aayegi', 'Intermediate', 'Sad', 'G', 1960],
    ['Aaj Sajan Mohe', 'Intermediate', 'Romantic', 'G', 1958],
    ['Babuji Dheere Chalna', 'Intermediate', 'Philosophical', 'G', 1954],
    ['Mere Jeevan Mein', 'Intermediate', 'Romantic', 'G', 1960],
  ]},
  'hemant-kumar': { name: 'Hemant Kumar', bio: 'Legendary Indian playback singer and composer. Known for his melodious voice.', songs: [
    ['Tum Pukar Lo', 'Intermediate', 'Romantic', 'G', 1958],
    ['Yeh Raat Bheegi Bheegi', 'Intermediate', 'Romantic', 'G', 1960],
    ['Na Jaane Kyun', 'Intermediate', 'Romantic', 'G', 1959],
    ['Mujhe Dard Ko', 'Intermediate', 'Sad', 'G', 1960],
    ['Beete Hue Din', 'Intermediate', 'Philosophical', 'G', 1961],
    ['Jalte Hain Jiske Liye', 'Intermediate', 'Sad', 'G', 1957],
    ['Insan Ki Aulad Hai', 'Intermediate', 'Philosophical', 'G', 1962],
    ['Chalo Dildar Chalo', 'Intermediate', 'Romantic', 'G', 1957],
    ['Tumhi Ne Mujhko', 'Intermediate', 'Romantic', 'G', 1959],
  ]},
  'talat-mahmood': { name: 'Talat Mahmood', bio: 'Legendary Indian playback singer. Known for his soulful and romantic voice.', songs: [
    ['Jalte Hain Jiske Liye', 'Intermediate', 'Sad', 'G', 1957],
    ['Phir Wohi Sham', 'Intermediate', 'Romantic', 'G', 1965],
    ['Ae Dil Mujhe Aisi Jagah', 'Intermediate', 'Romantic', 'G', 1962],
    ['Maine Shart Pe Jaan', 'Intermediate', 'Romantic', 'G', 1959],
    ['Pyar Mein Sadqe', 'Intermediate', 'Romantic', 'G', 1958],
    ['Bachpan Ke Din', 'Intermediate', 'Nostalgic', 'G', 1960],
    ['Sham-E-Gham Ki Kasam', 'Intermediate', 'Sad', 'G', 1961],
    ['Hai Duniya Mein', 'Intermediate', 'Philosophical', 'G', 1959],
  ]},
  'ar-rahman': { name: 'A.R. Rahman', bio: 'Indian composer, singer, and music producer. Academy Award winner. The Mozart of Madras.', songs: [
    ['Jai Ho', 'Intermediate', 'Patriotic', 'G', 2008],
    ['Tumhi Dekho Na', 'Intermediate', 'Romantic', 'G', 2008],
    ['Mitwa', 'Intermediate', 'Romantic', 'G', 2006],
    ['Maa Tujhhe Salaam', 'Intermediate', 'Patriotic', 'G', 1999],
    ['Dil Se Re', 'Intermediate', 'Romantic', 'G', 1998],
    ['Satrangi Re', 'Intermediate', 'Romantic', 'G', 1998],
    ['Rang De Basanti', 'Intermediate', 'Patriotic', 'G', 2006],
    ['Kabhi Kabhi Aditi', 'Intermediate', 'Romantic', 'G', 2008],
    ['Chaiyya Chaiyya', 'Intermediate', 'Dance', 'G', 1998],
    ['Vande Mataram', 'Intermediate', 'Patriotic', 'G', 1997],
    ['O Saya', 'Intermediate', 'Fusion', 'G', 2008],
    ['Maahi Ve', 'Intermediate', 'Romantic', 'G', 2002],
  ]},
  'sonu-nigam': { name: 'Sonu Nigam', bio: 'Indian playback singer. One of the most versatile and popular modern singers.', songs: [
    ['Kal Ho Naa Ho', 'Intermediate', 'Sad', 'G', 2003],
    ['Saathiya', 'Intermediate', 'Romantic', 'G', 2002],
    ['Woh Lamhe', 'Intermediate', 'Sad', 'G', 2005],
    ['Dil Ne Yeh Kaha', 'Intermediate', 'Romantic', 'G', 2002],
    ['Mohabbatein', 'Intermediate', 'Romantic', 'G', 2000],
    ['Main Agar Saamne', 'Intermediate', 'Romantic', 'G', 1998],
    ['Jeena Sirf Merre Liye', 'Intermediate', 'Romantic', 'G', 2002],
    ['Abhi Mujh Mein Kahin', 'Intermediate', 'Sad', 'G', 2004],
    ['Tumse Milna', 'Intermediate', 'Romantic', 'G', 2004],
    ['Chanda Ki Zindagi', 'Intermediate', 'Philosophical', 'G', 1998],
    ['Sanam Mere Sanam', 'Intermediate', 'Romantic', 'G', 2001],
    ['Do Dil', 'Intermediate', 'Romantic', 'G', 1999],
  ]},
  'kumar-sanu': { name: 'Kumar Sanu', bio: 'Indian playback singer. King of romantic songs in the 1990s.', songs: [
    ['Maine Pyar Kiya', 'Intermediate', 'Romantic', 'G', 1989],
    ['Dil Deewana Bin Sajna Ke', 'Intermediate', 'Romantic', 'G', 1992],
    ['Jaati Hoon Main', 'Intermediate', 'Romantic', 'G', 1995],
    ['Ek Ladki Ko Dekha', 'Intermediate', 'Romantic', 'G', 1994],
    ['Pehli Baar Mile Hain', 'Intermediate', 'Romantic', 'G', 1993],
    ['Tujhe Dekha To', 'Intermediate', 'Romantic', 'G', 1996],
    ['Main Duniya Bhula Doonga', 'Intermediate', 'Romantic', 'G', 1992],
    ['Dil Ka Kya Karein', 'Intermediate', 'Sad', 'G', 1994],
    ['Sochenge Tumhe Pyar', 'Intermediate', 'Romantic', 'G', 1993],
    ['Hum Toh Dil Se Haar', 'Intermediate', 'Romantic', 'G', 1995],
    ['Mera Chand Mujhe Aaya Hai', 'Intermediate', 'Romantic', 'G', 1991],
    ['O Priya Priya', 'Intermediate', 'Romantic', 'G', 1992],
  ]},
  'alka-yagnik': { name: 'Alka Yagnik', bio: 'Indian playback singer. Leading female playback singer of the 1990s and 2000s.', songs: [
    ['Dil Hai Chhota Sa', 'Intermediate', 'Romantic', 'G', 1992],
    ['Taal Se Taal Mila', 'Intermediate', 'Romantic', 'G', 1999],
    ['Aaja Piya', 'Intermediate', 'Romantic', 'G', 2004],
    ['Kuchh Kuchh Hota Hai', 'Intermediate', 'Romantic', 'G', 1998],
    ['Dilwale Dulhania Le Jayenge', 'Intermediate', 'Romantic', 'G', 1995],
    ['Raja Ko Rani Se', 'Intermediate', 'Romantic', 'G', 1996],
    ['Pardes', 'Intermediate', 'Romantic', 'G', 1997],
    ['Yeh Jawani Hadh Kar De', 'Intermediate', 'Dance', 'G', 1996],
    ['Mere Mehboob Mere Sanam', 'Intermediate', 'Romantic', 'G', 1997],
    ['Aankhon Mein Tera Hi Chehra', 'Intermediate', 'Romantic', 'G', 2000],
    ['Tu Mile Dil Khile', 'Intermediate', 'Romantic', 'G', 1998],
    ['Kehti Hai Dil Ki Lagi', 'Intermediate', 'Romantic', 'G', 1992],
  ]},
  'shreya-ghoshal': { name: 'Shreya Ghoshal', bio: 'Indian playback singer. One of the most popular and versatile contemporary singers.', songs: [
    ['Bairi Piya', 'Intermediate', 'Romantic', 'G', 2005],
    ['Jaadu Hai Nasha Hai', 'Intermediate', 'Romantic', 'G', 2004],
    ['Dola Re Dola', 'Intermediate', 'Classical', 'G', 2002],
    ['Agar Tum Mil Jao', 'Intermediate', 'Sad', 'G', 2005],
    ['Piyu Bole', 'Intermediate', 'Romantic', 'G', 2010],
    ['Saans', 'Intermediate', 'Romantic', 'G', 2008],
    ['Teri Meri', 'Intermediate', 'Romantic', 'G', 2011],
    ['Chikni Chameli', 'Intermediate', 'Dance', 'G', 2012],
    ['Sun Raha Hai', 'Intermediate', 'Sad', 'G', 2010],
    ['Deewani Mastani', 'Intermediate', 'Romantic', 'G', 2015],
    ['Ghoomar', 'Intermediate', 'Classical', 'G', 2018],
    ['Mere Dholna', 'Intermediate', 'Sad', 'G', 2005],
  ]},
  'udit-narayan': { name: 'Udit Narayan', bio: 'Indian playback singer. Leading male playback singer of the 1990s.', songs: [
    ['Pehla Nasha', 'Intermediate', 'Romantic', 'G', 1993],
    ['Tu Cheez Badi Hai', 'Intermediate', 'Dance', 'G', 1996],
    ['Mere Rang Mein', 'Intermediate', 'Romantic', 'G', 1997],
    ['Chand Taare', 'Intermediate', 'Romantic', 'G', 1998],
    ['Dil To Pagal Hai', 'Intermediate', 'Romantic', 'G', 1997],
    ['Bole Chudiyan', 'Intermediate', 'Celebratory', 'G', 2000],
    ['Humko Sirf Tumse', 'Intermediate', 'Romantic', 'G', 1999],
    ['Mujhe Maaf Karna', 'Intermediate', 'Sad', 'G', 1995],
    ['Yeh Dil Deewana', 'Intermediate', 'Romantic', 'G', 1996],
    ['Dil Ne Yeh Kaha', 'Intermediate', 'Romantic', 'G', 2002],
    ['Sajna Sajna', 'Intermediate', 'Romantic', 'G', 2003],
    ['Mohabbat Hai', 'Intermediate', 'Romantic', 'G', 1994],
  ]},
  'kk': { name: 'KK', bio: 'Indian playback singer. Known for his versatile voice and soulful renditions.', songs: [
    ['Pal', 'Intermediate', 'Romantic', 'G', 1999],
    ['Tadap Tadap', 'Intermediate', 'Sad', 'G', 2001],
    ['Aap Ki Khatir', 'Intermediate', 'Romantic', 'G', 2006],
    ['Dil Ibaadat', 'Intermediate', 'Romantic', 'G', 2008],
    ['Zara Sa', 'Intermediate', 'Romantic', 'G', 2008],
    ['Beete Lamhein', 'Intermediate', 'Sad', 'G', 2005],
    ['O Meri Jaan', 'Intermediate', 'Romantic', 'G', 2008],
    ['Sach Keh Raha Hai', 'Intermediate', 'Romantic', 'G', 2007],
    ['Yaaron', 'Intermediate', 'Friendship', 'G', 1999],
    ['Dil Kyun Yeh Mera', 'Intermediate', 'Romantic', 'G', 2009],
    ['Mujhe Tum Nazar Se', 'Intermediate', 'Romantic', 'G', 2005],
    ['Tu Jo Mila', 'Intermediate', 'Romantic', 'G', 2010],
  ]},
  'shaan': { name: 'Shaan', bio: 'Indian playback singer. Known for his youthful and energetic voice.', songs: [
    ['Chand Sifarish', 'Intermediate', 'Romantic', 'G', 2005],
    ['Jhootha Hi Sahi', 'Intermediate', 'Romantic', 'G', 2007],
    ['Dus Bahane', 'Intermediate', 'Dance', 'G', 2003],
    ['Woh Pehli Baar', 'Intermediate', 'Romantic', 'G', 2004],
    ['Maine Jaana Na', 'Intermediate', 'Romantic', 'G', 2005],
    ['Jab Se Tere Naina', 'Intermediate', 'Romantic', 'G', 2004],
    ['Nikamma Kiya', 'Intermediate', 'Romantic', 'G', 2006],
    ['Layi Vi Na Gayi', 'Intermediate', 'Dance', 'G', 2007],
    ['Tanha Dil', 'Intermediate', 'Sad', 'G', 2004],
    ['Sajna Ji', 'Intermediate', 'Romantic', 'G', 2006],
  ]},
  'mohit-chauhan': { name: 'Mohit Chauhan', bio: 'Indian playback singer. Known for his soulful and soothing voice.', songs: [
    ['Tum Se Hi', 'Intermediate', 'Romantic', 'G', 2008],
    ['Pehli Baar', 'Intermediate', 'Romantic', 'G', 2009],
    ['Jo Bhi Main', 'Intermediate', 'Romantic', 'G', 2010],
    ['Sadda Haq', 'Intermediate', 'Patriotic', 'G', 2010],
    ['Phir Se Ud Chala', 'Intermediate', 'Inspirational', 'G', 2011],
    ['Barfi', 'Intermediate', 'Romantic', 'G', 2012],
    ['Matargashti', 'Intermediate', 'Playful', 'G', 2013],
    ['Kahin Na Kahin', 'Intermediate', 'Romantic', 'G', 2010],
    ['Paisa Ye Paisa', 'Intermediate', 'Playful', 'G', 2011],
    ['Akkad Bakkad', 'Intermediate', 'Playful', 'G', 2010],
  ]},
  'atif-aslam': { name: 'Atif Aslam', bio: 'Pakistani playback singer. Popular across India and Pakistan for romantic songs.', songs: [
    ['Tere Bin', 'Intermediate', 'Romantic', 'G', 2008],
    ['Pehli Nazar Mein', 'Intermediate', 'Romantic', 'G', 2005],
    ['Woh Lamhey', 'Intermediate', 'Romantic', 'G', 2008],
    ['Jeene Laga Hoon', 'Intermediate', 'Romantic', 'G', 2011],
    ['Piya O Re Piya', 'Intermediate', 'Romantic', 'G', 2012],
    ['Dil Meri Na Sune', 'Intermediate', 'Sad', 'G', 2010],
    ['Mushkoora', 'Intermediate', 'Romantic', 'G', 2012],
    ['Be Intehaan', 'Intermediate', 'Romantic', 'G', 2008],
    ['Toota Jo Kabhi Taara', 'Intermediate', 'Sad', 'G', 2010],
    ['Rabba', 'Intermediate', 'Sad', 'G', 2009],
    ['Aadat', 'Intermediate', 'Sad', 'G', 2004],
    ['Hona Tha Pyar', 'Intermediate', 'Romantic', 'G', 2011],
  ]},
  'neha-kakkar': { name: 'Neha Kakkar', bio: 'Indian playback singer. Popular modern Bollywood voice.', songs: [
    ['Sunny Sunny', 'Intermediate', 'Dance', 'G', 2014],
    ['Chhote Chhote Peg', 'Intermediate', 'Dance', 'G', 2017],
    ['Oh Humsafar', 'Intermediate', 'Romantic', 'G', 2015],
    ['Gilehriyaan', 'Intermediate', 'Dance', 'G', 2017],
    ['Tu Hi Yaar Mera', 'Intermediate', 'Romantic', 'G', 2018],
    ['O Saki Saki', 'Intermediate', 'Dance', 'G', 2019],
    ['Dil Todeya', 'Intermediate', 'Dance', 'G', 2020],
    ['Kala Chashma', 'Intermediate', 'Dance', 'G', 2016],
    ['Mile Ho Tum', 'Intermediate', 'Romantic', 'G', 2014],
    ['Bebo', 'Intermediate', 'Dance', 'G', 2018],
    ['Main Tumhara', 'Intermediate', 'Romantic', 'G', 2015],
    ['Coca Cola', 'Intermediate', 'Dance', 'G', 2017],
  ]},
  'badshah': { name: 'Badshah', bio: 'Indian rapper and singer. Pioneer of commercial hip-hop in India.', songs: [
    ['DJ Waley Babu', 'Intermediate', 'Hip Hop', 'G', 2015],
    ['Mercy', 'Intermediate', 'Hip Hop', 'G', 2016],
    ['Kala Chashma', 'Intermediate', 'Hip Hop', 'G', 2016],
    ['Saturday Saturday', 'Intermediate', 'Dance', 'G', 2016],
    ['Abhi Toh Party Shuru Hui Hai', 'Intermediate', 'Dance', 'G', 2016],
    ['Paani Paani', 'Intermediate', 'Dance', 'G', 2017],
    ['Genda Phool', 'Intermediate', 'Dance', 'G', 2020],
    ['Proper Patola', 'Intermediate', 'Dance', 'G', 2016],
    ['Saari Aakh', 'Intermediate', 'Hip Hop', 'G', 2017],
    ['Sheher', 'Intermediate', 'Hip Hop', 'G', 2016],
    ['B.A.S.E.', 'Intermediate', 'Hip Hop', 'G', 2017],
    ['Makhna', 'Intermediate', 'Dance', 'G', 2019],
  ]},
  'nusrat-fateh-ali-khan': { name: 'Nusrat Fateh Ali Khan', bio: 'Pakistani qawwali singer. The Shahenshah of Qawwali.', songs: [
    ['Allah Hoo', 'Intermediate', 'Qawwali', 'G', 1990],
    ['Tumhe Dillagi', 'Intermediate', 'Qawwali', 'G', 1991],
    ['Mast Nazron Se', 'Intermediate', 'Qawwali', 'G', 1992],
    ['Dil Haray Nu', 'Intermediate', 'Qawwali', 'G', 1993],
    ['Sanson Ki Mala', 'Intermediate', 'Qawwali', 'G', 1990],
    ['Piya Re Piya Re', 'Intermediate', 'Qawwali', 'G', 1992],
    ['Mera Piya Ghar Aaya', 'Intermediate', 'Qawwali', 'G', 1991],
    ['Afreen Afreen', 'Intermediate', 'Qawwali', 'G', 1994],
    ['Kinna Sohna', 'Intermediate', 'Qawwali', 'G', 1993],
    ['Rabba Sacheya', 'Intermediate', 'Qawwali', 'G', 1990],
    ['Tere Bin Nahin', 'Intermediate', 'Qawwali', 'G', 1992],
    ['Yeh Jo Halka Halka', 'Intermediate', 'Qawwali', 'G', 1991],
  ]},
  'jagjit-singh': { name: 'Jagjit Singh', bio: 'Indian ghazal singer. The Ghazal King.', songs: [
    ['Tum Itna Jo Muskura Rahe Ho', 'Intermediate', 'Ghazal', 'G', 1988],
    ['Hoshwalon Ko Khabar Kya', 'Intermediate', 'Ghazal', 'G', 1982],
    ['Jhuki Jhuki Si Nazar', 'Intermediate', 'Ghazal', 'G', 1985],
    ['Tera Chehra', 'Intermediate', 'Ghazal', 'G', 1990],
    ['Saathiya Tune Kya Kiya', 'Intermediate', 'Ghazal', 'G', 1994],
    ['Dil To Pagal Hai', 'Intermediate', 'Ghazal', 'G', 1997],
    ['Chitthi Na Koi Sandes', 'Intermediate', 'Ghazal', 'G', 1990],
    ['Maine Shayar To Nahin', 'Intermediate', 'Ghazal', 'G', 1992],
    ['Badi Nazuk Hai', 'Intermediate', 'Ghazal', 'G', 1988],
    ['Woh Kagaz Ki Kashti', 'Intermediate', 'Ghazal', 'G', 1986],
    ['Ajeeb Dastan', 'Intermediate', 'Ghazal', 'G', 1985],
    ['Kal Chaudhvin Ki Raat', 'Intermediate', 'Ghazal', 'G', 1988],
  ]},
  'hariharan': { name: 'Hariharan', bio: 'Indian playback singer and ghazal singer. Known for his rich voice.', songs: [
    ['Roobaroo', 'Intermediate', 'Ghazal', 'G', 2005],
    ['Mere Dushman', 'Intermediate', 'Ghazal', 'G', 1995],
    ['Dil Ka Kya', 'Intermediate', 'Ghazal', 'G', 1992],
    ['Tu Hi Re', 'Intermediate', 'Romantic', 'G', 2002],
    ['Kabhi Alvida Naa Kehna', 'Intermediate', 'Romantic', 'G', 2006],
    ['Tum Gaye', 'Intermediate', 'Sad', 'G', 1998],
    ['Aaja Piya', 'Intermediate', 'Romantic', 'G', 2004],
    ['Chhupana Bhi Nahi Aata', 'Intermediate', 'Romantic', 'G', 2005],
    ['Jiya Jale', 'Intermediate', 'Romantic', 'G', 2000],
    ['Bhar De Jholi', 'Intermediate', 'Devotional', 'G', 2008],
    ['Kaisi Hai Yeh', 'Intermediate', 'Romantic', 'G', 2003],
    ['Allah Jaane', 'Intermediate', 'Romantic', 'G', 2006],
  ]},
  'kavita-krishnamurthy': { name: 'Kavita Krishnamurthy', bio: 'Indian playback singer. Known for her versatile classical and modern singing.', songs: [
    ['Mera Piya Ghar Aaya', 'Intermediate', 'Romantic', 'G', 1998],
    ['Dholna', 'Intermediate', 'Classical', 'G', 1999],
    ['Bairan Piya', 'Intermediate', 'Romantic', 'G', 2000],
    ['Chanda Se Hogi', 'Intermediate', 'Romantic', 'G', 1993],
    ['Hum To Dil Se Haar', 'Intermediate', 'Romantic', 'G', 1995],
    ['Pyar Ke Liye', 'Intermediate', 'Romantic', 'G', 1996],
    ['Hamari Shaadi Mein', 'Intermediate', 'Celebratory', 'G', 1998],
    ['Aane Wala Pal', 'Intermediate', 'Philosophical', 'G', 1994],
  ]},
  'shankar-mahadevan': { name: 'Shankar Mahadevan', bio: 'Indian playback singer and music composer. One third of Shankar-Ehsaan-Loy.', songs: [
    ['Mitwa', 'Intermediate', 'Romantic', 'G', 2006],
    ['Breathless', 'Intermediate', 'Experimental', 'G', 1998],
    ['Maahi Ve', 'Intermediate', 'Romantic', 'G', 2002],
    ['Woh Jab Yaad Aaye', 'Intermediate', 'Sad', 'G', 2005],
    ['Is Pal', 'Intermediate', 'Romantic', 'G', 2005],
    ['Koi Kahe Kehta Rahe', 'Intermediate', 'Romantic', 'G', 2000],
    ['Yeh Tara', 'Intermediate', 'Romantic', 'G', 2007],
    ['Ek Pal Ka Yeh Jeevan', 'Intermediate', 'Philosophical', 'G', 2003],
    ['Dil Chahta Hai', 'Intermediate', 'Romantic', 'G', 2001],
    ['Kal Ho Na Ho', 'Intermediate', 'Sad', 'G', 2003],
    ['Main Yahaan Hoon', 'Intermediate', 'Philosophical', 'G', 2006],
    ['Janam Samjha Karo', 'Intermediate', 'Romantic', 'G', 1999],
  ]},
  'abhijeet': { name: 'Abhijeet Bhattacharya', bio: 'Indian playback singer. Known for his romantic songs in the 1990s and 2000s.', songs: [
    ['Mast Mast', 'Intermediate', 'Romantic', 'G', 1999],
    ['Main Koi Aisa Geet', 'Intermediate', 'Romantic', 'G', 2000],
    ['Tumse Milne Ko Dil', 'Intermediate', 'Romantic', 'G', 1998],
    ['Dil Ne Yeh Kaha', 'Intermediate', 'Romantic', 'G', 2002],
    ['Aati Kya Khandala', 'Intermediate', 'Playful', 'G', 1997],
    ['Ban Ban Ban', 'Intermediate', 'Dance', 'G', 1999],
    ['Chori Chori Jab', 'Intermediate', 'Romantic', 'G', 2000],
    ['Mujhe Pyaar Hua', 'Intermediate', 'Romantic', 'G', 2001],
  ]},
  'anuradha-paudwal': { name: 'Anuradha Paudwal', bio: 'Indian playback singer. Known for devotional and romantic songs.', songs: [
    ['Dil Hai Deewana', 'Intermediate', 'Romantic', 'G', 1992],
    ['Ek Do Teen', 'Intermediate', 'Dance', 'G', 1988],
    ['Mere Rang Mein', 'Intermediate', 'Romantic', 'G', 1997],
    ['Aaja Re Mere Khwabon Mein', 'Intermediate', 'Romantic', 'G', 1993],
    ['Saat Samundar', 'Intermediate', 'Romantic', 'G', 1994],
    ['Tu Hi Mera Chand', 'Intermediate', 'Romantic', 'G', 1995],
    ['Aankhen Khuli', 'Intermediate', 'Romantic', 'G', 1996],
    ['Pyar Ka Devta', 'Intermediate', 'Romantic', 'G', 1992],
    ['Jhula Bahon Ka', 'Intermediate', 'Romantic', 'G', 1993],
  ]},
  'ghulam-ali': { name: 'Ghulam Ali', bio: 'Pakistani ghazal singer. Master of the Patiala gharana.', songs: [
    ['Chupke Chupke Raat Din', 'Intermediate', 'Ghazal', 'G', 1980],
    ['Hungama Hai Kyon Barpa', 'Intermediate', 'Ghazal', 'G', 1982],
    ['Dil Mein Tujhe Bithakar', 'Intermediate', 'Ghazal', 'G', 1981],
    ['Aaj Mere Dil Mein', 'Intermediate', 'Ghazal', 'G', 1983],
    ['Ishq Mein', 'Intermediate', 'Ghazal', 'G', 1985],
    ['Pyar Ka Pehla Khat', 'Intermediate', 'Ghazal', 'G', 1980],
    ['Tere Pyar Mein', 'Intermediate', 'Ghazal', 'G', 1982],
    ['Mere Dil Mein Hai Tu', 'Intermediate', 'Ghazal', 'G', 1984],
  ]},
  'sunidhi-chauhan': { name: 'Sunidhi Chauhan', bio: 'Indian playback singer. Known for her powerful and versatile voice.', songs: [
    ['Sheila Ki Jawani', 'Intermediate', 'Dance', 'G', 2010],
    ['Dance Pe Chance', 'Intermediate', 'Dance', 'G', 2009],
    ['Beedi', 'Intermediate', 'Dance', 'G', 2005],
    ['Aaja Nachle', 'Intermediate', 'Dance', 'G', 2007],
    ['Sajna Ve Sajna', 'Intermediate', 'Romantic', 'G', 2009],
    ['Mere Haath Mein', 'Intermediate', 'Romantic', 'G', 2006],
    ['Kaisi Hai Yeh', 'Intermediate', 'Romantic', 'G', 2003],
    ['Chhaliya', 'Intermediate', 'Dance', 'G', 2006],
    ['Desi Girl', 'Intermediate', 'Dance', 'G', 2008],
    ['Halki Halki', 'Intermediate', 'Romantic', 'G', 2009],
    ['Kukkad', 'Intermediate', 'Dance', 'G', 2007],
    ['Mast Mast', 'Intermediate', 'Dance', 'G', 2005],
  ]},
}

// ---------------------------------------------------------------------------
// Generate SQL
// ---------------------------------------------------------------------------
const allArtists = { ...engArtists, ...nepArtists, ...hinArtists }
const artistNames = Object.keys(allArtists)
const OUT_PATH = path.resolve(__dirname, '..', 'supabase/migrations/20250715000000_seed_1k.sql')

let sql = `-- Migration: Seed 1k unique songs (English, Nepali, Hindi)
-- Generated: ${new Date().toISOString()}
-- ${artistNames.length} artists (${Object.keys(engArtists).length} English, ${Object.keys(nepArtists).length} Nepali, ${Object.keys(hinArtists).length} Hindi)

BEGIN;

INSERT INTO artist (name, slug, bio, "isActive") VALUES\n`

const artistRows = artistNames.map((slug) => {
  const a = allArtists[slug]
  return `  (${escapeVal(a.name)}, ${escapeVal(slug)}, ${escapeVal(a.bio || null)}, TRUE)`
})
sql += artistRows.join(',\n') + '\n'
sql += `ON CONFLICT (slug) DO NOTHING;\n\n`

sql += `-- Songs\n`
let totalSongs = 0

for (const [slug, artist] of Object.entries(allArtists)) {
  for (const [title, difficulty, genre, key, year] of artist.songs) {
    const songSlug = toSlug(title) + '-' + slug
    const cnt = content(title, artist.name, key)

    sql += `INSERT INTO song (title, slug, "artistId", difficulty, genre, key, year, content, "isActive")\n`
    sql += `VALUES (${escapeVal(title)}, ${escapeVal(songSlug)}, (SELECT id FROM artist WHERE slug = ${escapeVal(slug)}),\n`
    sql += `  ${escapeVal(difficulty)}, ${escapeVal(genre)}, ${escapeVal(key)}, ${escapeVal(year)},\n`
    sql += `  $song_content$${cnt}$song_content$,\n`
    sql += `  TRUE)\n`
    sql += `ON CONFLICT (slug) DO NOTHING;\n`
    totalSongs++
  }
}

// ---- Extra songs to push total to ~1000 ----
const extraSongs = {
  'radiohead': [['Let Down', 'Intermediate', 'Alternative', 'G', 1997], ['Lucky', 'Intermediate', 'Alternative', 'G', 1997], ['There There', 'Intermediate', 'Alternative', 'G', 2003]],
  'the-clash': [['Stay Free', 'Intermediate', 'Punk', 'G', 1978], ['Tommy Gun', 'Intermediate', 'Punk', 'G', 1978], ['Guns of Brixton', 'Intermediate', 'Punk', 'Am', 1979]],
  'black-sabbath': [['Into the Void', 'Advanced', 'Heavy Metal', 'E', 1971], ['Snowblind', 'Advanced', 'Heavy Metal', 'E', 1972], ['Sabbath Bloody Sabbath', 'Advanced', 'Heavy Metal', 'G', 1973]],
  'iron-maiden': [['Flight of Icarus', 'Advanced', 'Heavy Metal', 'G', 1983], ['Can I Play with Madness', 'Advanced', 'Heavy Metal', 'G', 1988], ['Phantom of the Opera', 'Advanced', 'Heavy Metal', 'Am', 1980]],
  'rush': [['Red Barchetta', 'Advanced', 'Progressive Rock', 'G', 1981], ['Xanadu', 'Advanced', 'Progressive Rock', 'G', 1977], ['La Villa Strangiato', 'Advanced', 'Instrumental', 'G', 1978]],
  'genesis': [['Firth of Fifth', 'Advanced', 'Progressive Rock', 'G', 1973], ['Supper\'s Ready', 'Advanced', 'Progressive Rock', 'G', 1972], ['Dancing with the Moonlit Knight', 'Advanced', 'Progressive Rock', 'G', 1973]],
  'depeche-mode': [['Stripped', 'Intermediate', 'Electronic', 'G', 1986], ['Master and Servant', 'Intermediate', 'Electronic', 'G', 1984], ['Somebody', 'Beginner', 'Electronic', 'G', 1984]],
  'talking-heads': [['Life During Wartime', 'Intermediate', 'New Wave', 'G', 1979], ['Crosseyed and Painless', 'Intermediate', 'New Wave', 'G', 1980], ['Take Me to the River', 'Intermediate', 'New Wave', 'G', 1978]],
  'the-smiths': [['Hand in Glove', 'Intermediate', 'Indie', 'G', 1983], ['Still Ill', 'Intermediate', 'Indie', 'G', 1984], ['Barbarism Begins at Home', 'Intermediate', 'Indie', 'G', 1985]],
  'elo': [['Strange Magic', 'Intermediate', 'Rock', 'G', 1975], ['Last Train to London', 'Intermediate', 'Rock', 'G', 1979], ['Rockaria!', 'Intermediate', 'Rock', 'G', 1977]],
  'supertramp': [['Fool\'s Overture', 'Advanced', 'Progressive Rock', 'G', 1979], ['Hide in Your Shell', 'Intermediate', 'Progressive Rock', 'G', 1974], ['School', 'Advanced', 'Progressive Rock', 'G', 1974]],
  'toto': [['Make Believe', 'Intermediate', 'Rock', 'G', 1982], ['I\'ll Supply the Love', 'Intermediate', 'Rock', 'G', 1978], ['Child\'s Anthem', 'Advanced', 'Instrumental', 'G', 1978]],
  'foreigner': [['That Was Yesterday', 'Intermediate', 'Rock', 'G', 1984], ['Long Long Way from Home', 'Intermediate', 'Rock', 'G', 1977], ['Head Games', 'Advanced', 'Rock', 'G', 1979]],
  'janis-joplin': [['Move Over', 'Intermediate', 'Blues Rock', 'G', 1970], ['Turtle Blues', 'Advanced', 'Blues', 'G', 1968], ['Work Me Lord', 'Advanced', 'Blues', 'G', 1969]],
  'grateful-dead': [['China Cat Sunflower', 'Intermediate', 'Psychedelic', 'G', 1970], ['I Know You Rider', 'Intermediate', 'Folk Rock', 'G', 1970], ['Bertha', 'Intermediate', 'Rock', 'G', 1971]],
  'earth-wind-fire': [['Can\'t Hide Love', 'Intermediate', 'R&B', 'G', 1975], ['That\'s the Way of the World', 'Intermediate', 'R&B', 'G', 1975], ['Jupiter', 'Intermediate', 'Funk', 'G', 1977]],
  'james-brown': [['Please Please Please', 'Intermediate', 'Soul', 'G', 1956], ['Try Me', 'Intermediate', 'Soul', 'G', 1958], ['Night Train', 'Intermediate', 'R&B', 'G', 1961]],
  'ray-charles': [['Let the Good Times Roll', 'Intermediate', 'R&B', 'G', 1959], ['Night Time Is the Right Time', 'Intermediate', 'R&B', 'G', 1959], ['I Got a Woman', 'Intermediate', 'R&B', 'G', 1954]],
  'madonna': [['Holiday', 'Intermediate', 'Pop', 'G', 1983], ['Lucky Star', 'Intermediate', 'Pop', 'G', 1983], ['Borderline', 'Intermediate', 'Pop', 'G', 1984]],
  'abba': [['The Name of the Game', 'Intermediate', 'Pop', 'G', 1977], ['Money Money Money', 'Intermediate', 'Pop', 'G', 1976], ['Honey Honey', 'Intermediate', 'Pop', 'G', 1974]],
  'bee-gees': [['Words', 'Intermediate', 'Pop', 'G', 1968], ['I Started a Joke', 'Intermediate', 'Pop', 'G', 1968], ['Massachusetts', 'Intermediate', 'Pop', 'G', 1967]],
  'whitney-houston': [['I\'m Your Baby Tonight', 'Intermediate', 'Pop', 'G', 1990], ['All the Man That I Need', 'Intermediate', 'Pop', 'G', 1990], ['Exhale', 'Intermediate', 'R&B', 'G', 1995]],
  'mariah-carey': [['Honey', 'Intermediate', 'Pop', 'G', 1997], ['I Still Believe', 'Intermediate', 'Pop', 'G', 1998], ['Touch My Body', 'Intermediate', 'Pop', 'G', 2008]],
  'taylor-swift': [['Tim McGraw', 'Beginner', 'Country Pop', 'G', 2006], ['Picture to Burn', 'Intermediate', 'Country Pop', 'G', 2006], ['Should\'ve Said No', 'Intermediate', 'Country Pop', 'G', 2006]],
  'backstreet-boys': [['Get Down', 'Intermediate', 'Pop', 'G', 1996], ['We\'ve Got It Goin\' On', 'Intermediate', 'Pop', 'G', 1995], ['Any Other Way', 'Intermediate', 'Pop', 'G', 1997]],
  'britney-spears': [['From the Bottom of My Broken Heart', 'Intermediate', 'Pop', 'G', 1999], ['Sometimes', 'Intermediate', 'Pop', 'G', 1999], ['Born to Make You Happy', 'Intermediate', 'Pop', 'G', 1999]],
  'duran-duran': [['Planet Earth', 'Intermediate', 'New Wave', 'G', 1981], ['New Moon on Monday', 'Intermediate', 'New Wave', 'G', 1983], ['A View to a Kill', 'Intermediate', 'New Wave', 'G', 1985]],
  'tears-for-fears': [['Pale Shelter', 'Intermediate', 'New Wave', 'G', 1982], ['Mothers Talk', 'Intermediate', 'New Wave', 'G', 1984], ['Woman in Chains', 'Intermediate', 'New Wave', 'G', 1989]],
  'amy-winehouse': [['Fuck Me Pumps', 'Intermediate', 'Soul', 'G', 2006], ['Help Yourself', 'Intermediate', 'Soul', 'G', 2006], ['In My Bed', 'Intermediate', 'Soul', 'G', 2006]],
  'alicia-keys': [['How Come You Don\'t Call Me', 'Intermediate', 'R&B', 'G', 2001], ['Un-thinkable', 'Intermediate', 'R&B', 'G', 2009], ['Try Sleeping with a Broken Heart', 'Intermediate', 'R&B', 'G', 2009]],
  'norah-jones': [['Seven Years', 'Intermediate', 'Jazz Pop', 'G', 2002], ['The Nearness of You', 'Beginner', 'Jazz Pop', 'G', 2002], ['Cold Cold Heart', 'Beginner', 'Jazz Pop', 'G', 2002]],
  'pink': [['Family Portrait', 'Intermediate', 'Pop', 'G', 2002], ['Don\'t Let Me Get Me', 'Intermediate', 'Pop Rock', 'G', 2001], ['Most Girls', 'Intermediate', 'Pop', 'G', 2000]],
  'avril-lavigne': [['Losing Grip', 'Advanced', 'Pop Punk', 'G', 2002], ['Nobody\'s Home', 'Intermediate', 'Pop Rock', 'G', 2004], ['He Wasn\'t', 'Intermediate', 'Pop Punk', 'G', 2004]],
  'kelly-clarkson': [['Low', 'Intermediate', 'Pop Rock', 'G', 2003], ['Walk Away', 'Intermediate', 'Pop Rock', 'G', 2005], ['Never Again', 'Intermediate', 'Pop Rock', 'G', 2007]],
  'pixies': [['Gigantic', 'Intermediate', 'Alternative', 'G', 1988], ['Velouria', 'Intermediate', 'Alternative', 'G', 1990], ['Here Comes Your Man', 'Intermediate', 'Alternative', 'G', 1989]],
  'shreya-sotang': [['Sapanama', 'Intermediate', 'Pop', 'G', 2020], ['Maya', 'Intermediate', 'Pop', 'G', 2021], ['Phool', 'Intermediate', 'Pop', 'G', 2021]],
  'melina-rai': [['Bishwas', 'Intermediate', 'Pop', 'G', 2021], ['Samjhana', 'Intermediate', 'Pop', 'G', 2022], ['Jindagi', 'Intermediate', 'Pop', 'G', 2022]],
  'saurabh-adhikari': [['Basanta', 'Intermediate', 'Folk Pop', 'G', 2021], ['Saili', 'Intermediate', 'Folk Pop', 'G', 2020], ['Aaja', 'Intermediate', 'Folk Pop', 'G', 2022]],
  'rajina-rimal': [['Bansuri', 'Intermediate', 'Folk', 'G', 2021], ['Aakh', 'Intermediate', 'Folk', 'G', 2022], ['Tara', 'Intermediate', 'Folk', 'G', 2022]],
  'anju-panta': [['Muskurahat', 'Intermediate', 'Pop', 'G', 2021], ['Dherai', 'Intermediate', 'Pop', 'G', 2022], ['Bihani', 'Intermediate', 'Pop', 'G', 2022]],
  'kunti-moktan': [['Timi', 'Intermediate', 'Folk', 'G', 2019], ['Saili', 'Intermediate', 'Folk', 'G', 2020], ['Gaun', 'Intermediate', 'Folk', 'G', 2021]],
  'nima-rumba': [['Timi Nai', 'Intermediate', 'Pop', 'G', 2021], ['Maya Ko', 'Intermediate', 'Pop', 'G', 2022], ['Bato', 'Intermediate', 'Pop', 'G', 2022]],
  'rajesh-payal-rai': [['Timi Ra Ma', 'Intermediate', 'Pop Rock', 'G', 2019], ['Aashish', 'Intermediate', 'Pop Rock', 'G', 2020], ['Mero', 'Intermediate', 'Pop Rock', 'G', 2021]],
  'phattiman-rajbhandari': [['Chautari', 'Intermediate', 'Folk', 'G', 2019], ['Dhaka', 'Intermediate', 'Folk', 'G', 2020], ['Topi', 'Intermediate', 'Folk', 'G', 2021]],
  'rohit-john-chettri': [['Aankha', 'Intermediate', 'Folk Rock', 'G', 2022], ['Phool Ko', 'Intermediate', 'Folk Rock', 'G', 2022], ['Himal', 'Intermediate', 'Folk Rock', 'G', 2022]],
  'underground-tropa': [['Andolan', 'Intermediate', 'Reggae', 'G', 2021], ['Samanata', 'Intermediate', 'Reggae', 'G', 2022], ['Ekta', 'Intermediate', 'Reggae', 'G', 2022]],
  'raju-lama': [['Damphu Bajau', 'Intermediate', 'Tamang Selo', 'G', 2021], ['Nache', 'Intermediate', 'Tamang Selo', 'G', 2022], ['Tamang', 'Intermediate', 'Tamang Selo', 'G', 2022]],
  'ram-chandra-kafle': [['Pokhara', 'Intermediate', 'Folk', 'G', 2019], ['Parbat', 'Intermediate', 'Folk', 'G', 2020], ['Tilicho', 'Intermediate', 'Folk', 'G', 2021]],
  'the-black-cats': [['Hami', 'Intermediate', 'Pop', 'G', 2011], ['Nayika', 'Intermediate', 'Pop', 'G', 2012], ['Pratibha', 'Intermediate', 'Pop', 'G', 2013]],
  'swor-samrat': [['Phool Ko', 'Intermediate', 'Pop Rock', 'G', 2022], ['Aankha', 'Intermediate', 'Pop Rock', 'G', 2022], ['Timro', 'Intermediate', 'Pop Rock', 'G', 2022]],
  'trishala-gurung': [['Phool', 'Intermediate', 'Pop', 'G', 2022], ['Timro Aankha', 'Intermediate', 'Pop', 'G', 2022], ['Mero Mann', 'Intermediate', 'Pop', 'G', 2022]],
  'sushma-shakya': [['Pahad', 'Intermediate', 'Folk', 'G', 2019], ['Koshi', 'Intermediate', 'Folk', 'G', 2020], ['Pokhara', 'Intermediate', 'Folk', 'G', 2021]],
  'kiran-pradhan': [['Muskura', 'Intermediate', 'Folk Pop', 'G', 2021], ['Anubhav', 'Intermediate', 'Folk Pop', 'G', 2022], ['Sambandha', 'Intermediate', 'Folk Pop', 'G', 2022]],
  'bijay-bdr-rana': [['Nepali', 'Intermediate', 'Folk', 'G', 2019], ['Gaunle', 'Intermediate', 'Folk', 'G', 2020], ['Pahadi', 'Intermediate', 'Folk', 'G', 2021]],
  'candrabali': [['Aakash', 'Intermediate', 'Folk', 'G', 2019], ['Parbati', 'Intermediate', 'Folk', 'G', 2020], ['Badal', 'Intermediate', 'Folk', 'G', 2021]],
  'lata-mangeshkar': [['Sala Main', 'Intermediate', 'Romantic', 'G', 1965], ['Aap Ki Nazron Ne', 'Intermediate', 'Romantic', 'G', 1964]],
  'kishore-kumar': [['Ek Haseena Thi', 'Intermediate', 'Romantic', 'G', 1971], ['Ami Je Tomar', 'Intermediate', 'Romantic', 'G', 1974]],
  'mohammad-rafi': [['Jaanam Jaanam', 'Intermediate', 'Romantic', 'G', 1968], ['Mere Mehboob Qayamat Hogi', 'Intermediate', 'Romantic', 'G', 1965]],
  'mukesh': [['Suhani Chandni', 'Intermediate', 'Romantic', 'G', 1970], ['Hariyala Haryala', 'Intermediate', 'Romantic', 'G', 1972]],
  'asha-bhosle': [['Bahut Door', 'Intermediate', 'Romantic', 'G', 1978], ['Dil Ko Maine', 'Intermediate', 'Romantic', 'G', 1979]],
  'manna-dey': [['Aye Malik', 'Intermediate', 'Devotional', 'G', 1968], ['Tu Pyar Ka Sagar', 'Intermediate', 'Romantic', 'G', 1969]],
  'geeta-dutt': [['Suno Suno', 'Intermediate', 'Romantic', 'G', 1962], ['Deewana Mujhko', 'Intermediate', 'Romantic', 'G', 1963]],
  'hemant-kumar': [['Gunguna Rahe Hain', 'Intermediate', 'Romantic', 'G', 1962], ['Jhanak Jhanak', 'Intermediate', 'Romantic', 'G', 1964]],
  'talat-mahmood': [['Mili Khak Mein', 'Intermediate', 'Sad', 'G', 1962], ['Mausam Hai Matwala', 'Intermediate', 'Romantic', 'G', 1963]],
  'ar-rahman': [['Ennavale', 'Intermediate', 'Romantic', 'G', 1999], ['Mozart of Madras', 'Intermediate', 'Instrumental', 'G', 2005]],
  'sonu-nigam': [['You Are My Soniya', 'Intermediate', 'Romantic', 'G', 2003], ['Aaja Nahin', 'Intermediate', 'Sad', 'G', 2005]],
  'kumar-sanu': [['Mujhe Pyar', 'Intermediate', 'Romantic', 'G', 1994], ['Tanha Dil', 'Intermediate', 'Sad', 'G', 1996]],
  'alka-yagnik': [['O Priya Priya', 'Intermediate', 'Romantic', 'G', 1995], ['Dil Darr', 'Intermediate', 'Romantic', 'G', 1997]],
  'shreya-ghoshal': [['Mere Dholna', 'Intermediate', 'Classical', 'G', 2005], ['Barso Re', 'Intermediate', 'Romantic', 'G', 2007]],
  'udit-narayan': [['Masti Masti', 'Intermediate', 'Romantic', 'G', 2000], ['Kabhi Khushi Kabhie Gham', 'Intermediate', 'Celebratory', 'G', 2001]],
  'kk': [['Tu Hi Meri Zindagi', 'Intermediate', 'Romantic', 'G', 2008], ['Aasman Ke', 'Intermediate', 'Romantic', 'G', 2009]],
  'shaan': [['Mausam', 'Intermediate', 'Romantic', 'G', 2008], ['Shakalaka Baby', 'Intermediate', 'Dance', 'G', 2005]],
  'mohit-chauhan': [['Saans', 'Intermediate', 'Romantic', 'G', 2011], ['Dooriyan', 'Intermediate', 'Sad', 'G', 2012]],
  'atif-aslam': [['Kuchh Is Tarah', 'Intermediate', 'Romantic', 'G', 2009], ['Jannat', 'Intermediate', 'Romantic', 'G', 2010]],
  'neha-kakkar': [['Dheere Dheere', 'Intermediate', 'Romantic', 'G', 2017], ['Hashtag', 'Intermediate', 'Dance', 'G', 2018]],
  'badshah': [['Move Your Body', 'Intermediate', 'Hip Hop', 'G', 2018], ['Sheher Ki Ladki', 'Intermediate', 'Hip Hop', 'G', 2019]],
  'nusrat-fateh-ali-khan': [['Haiderium', 'Intermediate', 'Qawwali', 'G', 1990], ['Mujhe Qabul', 'Intermediate', 'Qawwali', 'G', 1992]],
  'jagjit-singh': [['Ahista Ahista', 'Intermediate', 'Ghazal', 'G', 1992], ['Yeh Dil', 'Intermediate', 'Ghazal', 'G', 1994]],
  'hariharan': [['Pyaar Ka Sama', 'Intermediate', 'Romantic', 'G', 2005], ['Humdum', 'Intermediate', 'Romantic', 'G', 2007]],
  'kavita-krishnamurthy': [['Lagi Lagi', 'Intermediate', 'Romantic', 'G', 1998], ['Saajan More', 'Intermediate', 'Romantic', 'G', 1999]],
  'shankar-mahadevan': [['Dil Chahta Hai Reprise', 'Intermediate', 'Romantic', 'G', 2002], ['Junoon', 'Intermediate', 'Romantic', 'G', 2004]],
  'abhijeet': [['Dil Hai Ke Manta Nahin', 'Intermediate', 'Romantic', 'G', 1999], ['Maine Dil Tujhko Diya', 'Intermediate', 'Romantic', 'G', 2000]],
  'anuradha-paudwal': [['Maine Chun Liya', 'Intermediate', 'Romantic', 'G', 1994], ['Dil Hai Deewana Reprise', 'Intermediate', 'Romantic', 'G', 1995]],
  'ghulam-ali': [['Mere Dil Mein Hai Tu', 'Intermediate', 'Ghazal', 'G', 1984], ['Dard Se', 'Intermediate', 'Ghazal', 'G', 1985]],
  'sunidhi-chauhan': [['Aaja Ve Mahi', 'Intermediate', 'Dance', 'G', 2007], ['Mehboob Mere', 'Intermediate', 'Romantic', 'G', 2008]],
}

sql += `-- Additional songs\n`
for (const [slug, songs] of Object.entries(extraSongs)) {
  const artist = allArtists[slug]
  const artistName = artist ? artist.name : slug
  for (const [title, difficulty, genre, key, year] of songs) {
    const songSlug = toSlug(title) + '-' + slug
    const cnt = content(title, artistName, key)
    sql += `INSERT INTO song (title, slug, "artistId", difficulty, genre, key, year, content, "isActive")\n`
    sql += `VALUES (${escapeVal(title)}, ${escapeVal(songSlug)}, (SELECT id FROM artist WHERE slug = ${escapeVal(slug)}),\n`
    sql += `  ${escapeVal(difficulty)}, ${escapeVal(genre)}, ${escapeVal(key)}, ${escapeVal(year)},\n`
    sql += `  $song_content$${cnt}$song_content$,\n`
    sql += `  TRUE)\n`
    sql += `ON CONFLICT (slug) DO NOTHING;\n`
    totalSongs++
  }
}

sql += `\nCOMMIT;\n`

fs.writeFileSync(OUT_PATH, sql, 'utf-8')
console.log(`✅ Generated ${OUT_PATH}`)
console.log(`   ${artistNames.length} artists, ${totalSongs} songs`)
console.log(`   English: ${Object.keys(engArtists).length} artists`)
console.log(`   Nepali: ${Object.keys(nepArtists).length} artists`)
console.log(`   Hindi: ${Object.keys(hinArtists).length} artists`)
